### ISSUE TITLE
Upload page designing with login  

### ISSUE THREAD

**Issue by Krina-Addweb** [snehal-addweb/Mortgagespeak#19]
1) Add value "Content Types" in  What are you uploading? & "Tag Types" in Tag My Content: with a dropdown
2) File must be less than 6MB (6MB Make it bold) 
3) Need to display "Allowed file types: pdf doc docx" in another line & also File types should be displayed in bold.
4)Need to remove Email Label from Email field & also add placeholder "Enter a Email Address"
5)Change Upload button text "Upload" to "Upload File"
6)Change Button text "Submit" to "Submit ! "
7) Need to design attached file section after attaching the file.
8)When we add any text in email box it should display full email address .

**Comment by roshni-addweb** [comment]
@Krina-Addweb Please test it.

**Comment by roshni-addweb** [comment]
@Krina-Addweb Please test it.
1) Add value "Content Types" in What are you uploading? & "Tag Types" in Tag My Content: with a dropdown
2) File must be less than 6MB (6MB Make it bold) 
3) Need to display "Allowed file types: pdf doc docx" in another line & also File types should be displayed in bold.
4)Need to remove Email Label from Email field & also add placeholder "Enter a Email Address"
5)Change Button text "Submit" to "Submit ! "
