### ISSUE TITLE
Interface for google adsense

### ISSUE THREAD

**Issue by saurabhd** [snehal-addweb/Mortgagespeak#42]
26.5 hours is approved for this task

**Comment by saurabhd** [comment]
Hello Greg,

Google AdSense task accomplished. Please follow below steps regarding Interface for google adsense:
1. New field "Company Tags (i.e. Yes/No)" added in Taxonomy called "Assign ad".
2. You have to select "Company Tags" as "Yes" to display only drupal ads on company pages. (i.e http://mortgage.saurabhdhariwal.com/1st-advantage-mtg).
3. If you select "NO" for "Company Tags" then It will work like as before.
4. Other steps follows as it is.

For E.G:

If I select "Company Tags" to "Yes" for "1st Advantage" company and there will be no Ads assign to that page. Then we'll display default Google Ads for this particular page.

Please check and let me know your thoughts.

Thanks!

**Comment by gatsby8870** [comment]
This works great. Thanks for all the hard work on this custom solution.
