### ISSUE TITLE
Development Server is offline

### ISSUE THREAD

**Issue by gatsby8870** [snehal-addweb/Mortgagespeak#43]
I am unable to access this server which significantly affects my ability to review items and provide new projects.

I would appreciate your feedback on its resolution.

http://mortgage.saurabhdhariwal.com/news

Thank you.

**Comment by saurabhd** [comment]
Server was down as I have lots of project in it so nothing is related to project its a normal case.

Its up and running fine.

**Comment by gatsby8870** [comment]
No worries. We spoke about it and it was fine.

Thanks for the follow up.
