### ISSUE TITLE
Estimate request: Company Newsrooms

### ISSUE THREAD

**Issue by gatsby8870** [snehal-addweb/Mortgagespeak#46]
This post is a request for a time estimate of the below work.

Please indicate per line item the hours required. This is b/c some items I may want/important and others I may not be able to do.

**New Work:**
1. Have the "Edit" link in lower gray row/right opens in new window. Please make same window. http://mortgage.saurabhdhariwal.com/my-page/tracked-news
2. Need a list of newsroom companies
   We created individual company news pages/newsrooms (great). But there is no "master" page that lists all company newsrooms to choose from or a way to search for a specific company.

Ideally, the master newsroom page should:
    - List companies alphabetically
    - Replace the row numbers in the center tab with the company's logos; Same approximate size as numbers
    - Clicks to hyperlinked company names go to their newsroom page
    - Add a search field in the lower gray row (containing their name) in the right corner (e.g. Search for a company newsroom)
    - Replace the "Blogs" and "Search" tabs in the center navigation bar to make room for a new tab called "Company Newsroom". See image. The "Blogs" and "Search" functionality should remain but not visible in this horizontal nav bar.

Other work items:
         - Add "+ follow" link for all news topics page so when clicked, it is added to their "My Page". Just like the company newsrooms do now.

```
    - Add search field for news, press releases and blogs each searching only that taxonomy (?) for the results
     - 
```

![default](https://cloud.githubusercontent.com/assets/18587752/14975493/daa0f07e-10c7-11e6-93dc-136cbc1a63f5.png)
![onclick](https://cloud.githubusercontent.com/assets/18587752/14975492/da9e031e-10c7-11e6-81b9-0da4bd97bcb7.png)

**Comment by saurabhd** [comment]
Hello Greg,

Here's the estimates and inputs:
1. Have the "Edit" link in lower gray row/right opens in new window. Please make same window. http://mortgage.saurabhdhariwal.com/my-page/tracked-news
   => 30 mins
2. Need a list of newsroom companies
   We created individual company news pages/newsrooms (great). But there is no "master" page that lists all company newsrooms to choose from or a way to search for a specific company.
   => 7 working hours 

Ideally, the master newsroom page should:
1. List companies alphabetically  
2. Replace the row numbers in the center tab with the company's logos; Same approximate size as numbers
   => If more than one company is selected at that time 1st selected company's logo will be displayed
    (For eg. If "a la mode" and "Core logic" is selected in one content then "Core logic's" logo will be displayed.)  
3. Clicks to hyperlinked company names go to their newsroom page  
4. Add a search field in the lower gray row (containing their name) in the right corner (e.g. Search for a company newsroom)
   => I assume that there will be one search box beside "Mortgage news from top media outlets united in one location" text and you can search for a company name.  
5. Replace the "Blogs" and "Search" tabs in the center navigation bar to make room for a new tab called "Company Newsroom". See image. The "Blogs" and "Search" functionality should remain but not visible in this horizontal nav bar.
1. Other work items: Add "+ follow" link for all news topics page so when clicked, it is added to their "My Page". Just like the company newsrooms do now.
   => 6 working hours
2. Add search field for news, press releases and blogs each searching only that taxonomy (?) for the results
   => Please elaborate and provide image for the same.
3. Design
   => 6 working hours
4. QA
   => 4 working hours

NOTE: Please provide an image for Company Newsroom Menu item. 

Let me know your thoughts for the same. 

Thanks!

**Comment by roshni-addweb** [comment]
@Krina-Addweb Please test 
1. Have the "Edit" link in lower gray row/right opens in new window. Please make same window. http://mortgage.saurabhdhariwal.com/my-page/tracked-news
2. Add "+ follow" link for all news topics page so when clicked, it is added to their "My Page". Just like the company newsrooms do now.

**Comment by Krina-Addweb** [comment]
Hello Greg,
Following points were done over http://mortgage.saurabhdhariwal.com/, please check & let me know if you have any query:
1. Have the "Edit" link in lower gray row/right opens in new window. Please make same window. http://mortgage.saurabhdhariwal.com/my-page/tracked-news
2. Add "+ follow" link for all news topics page so when clicked, it is added to their "My Page". Just like the company newsrooms do now.

**Comment by saurabhd** [comment]
@gatsby8870 

Further, please provide your inputs regarding: 

"Add search field for news, press releases and blogs each searching only that taxonomy (?) for the results
=> Please elaborate and provide image for the same."

Thanks
Saurabh

**Comment by gatsby8870** [comment]
Hello.

I have authorized this project as written and will deliver the requested items.

Attached are two of those items: "NOTE: Please provide an image for Company Newsroom Menu item."

OnClick.png: this represents the menu tab on user click
Default.png: this represents the menu tab on a non-clicked, default state

The center table can be ignored for these menu item images.

Thank you!

![default](https://cloud.githubusercontent.com/assets/18587752/15021317/b929af10-11eb-11e6-8851-37c4cdc26e56.png)
![onclick](https://cloud.githubusercontent.com/assets/18587752/15021318/b92c1f16-11eb-11e6-8d05-b66bdf546ba6.png)

**Comment by roshni-addweb** [comment]
@Krina-Addweb Please Test 
1. Need a list of newsroom companies
   We created individual company news pages/newsrooms (great). But there is no "master" page that lists all company newsrooms to choose from or a way to search for a specific company.

Ideally, the master newsroom page should:
1. List companies alphabetically  
2. Replace the row numbers in the center tab with the company's logos; Same approximate size as numbers
   => If more than one company is selected at that time 1st selected company's logo will be displayed
   (For eg. If "a la mode" and "Core logic" is selected in one content then "Core logic's" logo will be displayed.)  
3. Clicks to hyperlinked company names go to their newsroom page  
4. Add a search field in the lower gray row (containing their name) in the right corner (e.g. Search for a company newsroom)
   => I assume that there will be one search box beside "Mortgage news from top media outlets united in one location" text and you can search for a company name.  
5. Replace the "Blogs" and "Search" tabs in the center navigation bar to make room for a new tab called "Company Newsroom". See image. The "Blogs" and "Search" functionality should remain but not visible in this horizontal nav bar.

**Comment by Krina-Addweb** [comment]
@roshni-addweb : Sorting is not working correctly when we create New Alpha-Content for any company in same condition searching works correctly.

**Comment by gatsby8870** [comment]
Regarding this query by your team:

Further, please provide your inputs regarding:

"Add search field for news, press releases and blogs each searching only that taxonomy (?) for the results
=> Please elaborate and provide image for the same."

Thanks
Saurabh"

This is a simple search field on the second gray row that enables searching for the particular taxonomy. For example the company newsroom page search field would provide results for company newsroom pages that match.

**Comment by Krina-Addweb** [comment]
Following points are done over mortgage.saurabhdhariwal.com:
1. Need a list of newsroom companies We created individual company news pages/newsrooms (great). But there is no "master" page that lists all company newsrooms to choose from or a way to search for a specific company.

Ideally, the master newsroom page should:
1) List companies alphabetically
2) Replace the row numbers in the center tab with the company's logos; Same approximate size as numbers => If more than one company is selected at that time 1st selected company's logo will be displayed (For eg. If "a la mode" and "Core logic" is selected in one content then "Core logic's" logo will be displayed.)
3) Clicks to hyperlinked company names go to their newsroom page
4) Add a search field in the lower gray row (containing their name) in the right corner (e.g. Search for a   company newsroom) => I assume that there will be one search box beside "Mortgage news from top media outlets united in one location" text and you can search for a company name.
5) Replace the "Blogs" and "Search" tabs in the center navigation bar to make room for a new tab called "Company Newsroom". See image. The "Blogs" and "Search" functionality should remain but not visible in this horizontal nav bar.

**Comment by saurabhd** [comment]
Hello Greg,

Some quick queries:
1. http://mortgage.saurabhdhariwal.com/all-companies - Currently I have kept filter for "Company tags" taxonomy. 

Further, If you require any other image in place of default image i.e "All" which is placed currently, then please provide me an image for the same.

NOTE: Default image would be displayed if you have not placed image for "Company Tag"  taxonomy term.  
1. http://mortgage.saurabhdhariwal.com/news - Which taxonomy filter should be placed here, "Company tags" or "News topics"?

Let me know your thoughts for the same. 

Thanks!

**Comment by gatsby8870** [comment]
The following are new updates for this project. The previous work was completed to my satisfaction.

Company Newsroom:
![loading-indicator](https://cloud.githubusercontent.com/assets/18587752/15170649/56a5e4fe-170d-11e6-8f48-dd283e6cd74d.png)
![wider-search-field-with-text-and-searching-image](https://cloud.githubusercontent.com/assets/18587752/15170650/56a6e782-170d-11e6-86f6-dcd368b43d8e.png)
![company-newsroom-page-with-updated-search](https://cloud.githubusercontent.com/assets/18587752/15170669/89b9473c-170d-11e6-9d84-4fe7779c5ad1.png)
1. Organize the center table's content by content's publishing date and not alphabetically by the company's name
2. Hyperlink the company's logo to their Company Newsroom page
3. Edit error message displayed when an entered search term displays no results. Instead of: "Page not found. The requested page "/taxonomy/term/" could not be found." state "No Company Newsroom found. Please try another term or use the Contact form for assistance."
4. Widen the search field to accomodate companies with longer names (see image).
5. Change the circular arrows next to the search field to the loading image by default on my existing Drupal site (see attached)
6. Add text within search field: "Enter company name for look-up". Use same font style as in gray row already
7. Add this updated search field to all individual company newsroom pages so users can search from individual pages as well the main newsroom page

**Comment by Krina-Addweb** [comment]
Following points are done over mortgage.saurabhdhariwal.com
1) Organize the center table's content by content's publishing date and not alphabetically by the company's name
2) Hyperlink the company's logo to their Company Newsroom page
3) Widen the search field to accomodate companies with longer names (see image).
4) Change the circular arrows next to the search field to the loading image by default on my existing Drupal site (see attached)
5) Add text within search field: "Enter company name for look-up". Use same font style as in gray row already

**Comment by gatsby8870** [comment]
Hello, here is some feedback:
1. On the upload form, it needs a period (".") after ""effective White Paper Promotion".
2. On form for same row as above, remove the blank space after the opening paranthesis.
3. There is now a search icon adjacent to the form field to search on the company newsroom lower gray row. This is supposed to be that blue spinning circle as in image. Looks to be default from Drupal for uploads. Thought we could use it.
4. The company logo hyperlink to individual company newsrooms should open in same window not new window

**Comment by Krina-Addweb** [comment]
@avani-addweb : 
1) For Search button placed in all individual company newsroom pages need for a proper clickable area.

@roshni-addweb :
1) For Search functionality in all individual company newsroom pages, partial search is not working correctly instead of displaying no result behaviour it shows continuously moving page loader.

**Comment by Krina-Addweb** [comment]
Work for Following points were done over mortgage.saurabhdhariwal.com: 
1) Add this updated search field to all individual company newsroom pages so users can search from individual pages as well the main newsroom page
2) Edit error message displayed when an entered search term displays no results. Instead of: "Page not found. The requested page "/taxonomy/term/" could not be found." state "No Company Newsroom found. Please try another term or use the Contact form for assistance."
3) On the upload form, it needs a period (".") after ""effective White Paper Promotion".
4) On form for same row as above, remove the blank space after the opening paranthesis.
5) There is now a search icon adjacent to the form field to search on the company newsroom lower gray row. This is supposed to be that blue spinning circle as in image. Looks to be default from Drupal for uploads. Thought we could use it.
6) The company logo hyperlink to individual company newsrooms should open in same window not new window

**Comment by gatsby8870** [comment]
Hello, regarding this issue, please go ahead and perform the task. I am looking to add a search field to the News, Press Release and Perspective pages to search for a keyword red or keywords only within that taxonomy.

I will provide an image tomorrow but you can begin on your end.

"Add search field for news, press releases and blogs each searching only that taxonomy (?) for the results".

Estimate 16 hours (?)

**Comment by saurabhd** [comment]
Okay, would be awaiting for an image. Can comment over estimates/queries once you provide me images. Thanks!

**Comment by gatsby8870** [comment]
Hello, here are the images and one image substitution for the "sign into Googke Docs" images currently used on the MyPage > RGA Activity page.

Attached are the search bar images for searchingwithtin the News, Press Releases and Perspective pages. Just searching and providing results for within that taxonomy only.

![image](https://cloud.githubusercontent.com/assets/18587752/15492676/896fb1a4-2143-11e6-9b85-41281dddd4e1.png)
![image](https://cloud.githubusercontent.com/assets/18587752/15492677/89869bda-2143-11e6-9600-dec84662a783.png)
![image](https://cloud.githubusercontent.com/assets/18587752/15492678/89899736-2143-11e6-8b9e-aede28893e87.png)
![image](https://cloud.githubusercontent.com/assets/18587752/15492679/898e9146-2143-11e6-9faf-aa9306a41008.png)

**Comment by Krina-Addweb** [comment]
Hello Greg,
Please check first point "Hello, here are the images and one image substitution for the "sign into Google Docs" images currently used on the MyPage > RGA Activity page." which is done over mortgage.saurabhdhariwal.com".

Thanks.

**Comment by Krina-Addweb** [comment]
Hello Greg , 

Following pending point is done over mortgage.saurabhdhariwal.com :
"Attached are the search bar images for searching within the News, Press Releases and Perspective pages. Just searching and providing results for within that taxonomy only."

Thanks
