### ISSUE TITLE
Misc Edits

### ISSUE THREAD

**Issue by gatsby8870** [snehal-addweb/Mortgagespeak#48]
Please perform these edits:
1. In the center horizontal tab:, change top row color of Company Newsroom tab (onclick) to: 3383cc, and change color of My Page tab (onlick) to: f07a22
2. Add the term "News" to all "News" topic pages. For example, change the lower gray row text from "AMC | + follow" to "AMC News | + follow"
3. On Upload form, in section "1. What Are You Uploading?, add to the second check box row (Perspective), this text at the end: "Learn about effective White Paper Promotion." Include this hyperlink and have it open in a new window. See attached
   ![remove](https://cloud.githubusercontent.com/assets/18587752/15170724/190faaa2-170e-11e6-8fd6-c48bd1ad6b2c.png)

![upload-form-update-with-document-hyperlink](https://cloud.githubusercontent.com/assets/18587752/15170717/0e140c10-170e-11e6-89e5-32d27c574500.png)
 image.
4. Within user profile, the "Advertising" and "Newsletter Distribution" forms show the form's name twice on this page. Please remove the hyperlinked blue names and the thin gray lines (see image).
5. For users with role "PR Activity", this page has a Google Doc iFrame. Sometimes the user is not logged into Google Docs and the iFrame is blank. If blank, can we show a text message somewhere "No Google Doc visible? Please sign in to Google Docs".
6. Link the "Sign in to google docs" button to open in a new window"

**Comment by saurabhd** [comment]
Hello Greg,

"Learn about effective White Paper Promotion." Include **this** hyperlink and have it open in a new window

> > Can you please provide me link for "this" please.

Thanks!

**Comment by gatsby8870** [comment]
Certainly!
Sorry, I guess the url did not come over on the copy/paste into GitHub:
http://mortgage.saurabhdhariwal.com/effective-promotion-white-paper

Date: Wed, 11 May 2016 03:13:08 -0700

**Comment by Krina-Addweb** [comment]
Following points are done over mortgage.saurabhdhariwal.com

1) In the center horizontal tab:, change top row color of Company Newsroom tab (onclick) to: 3383cc, and change color of My Page tab (onlick) to: f07a22

2) Add the term "News" to all "News" topic pages. For example, change the lower gray row text from "AMC | + follow" to "AMC News | + follow"

3) On Upload form, in section "1. What Are You Uploading?, add to the second check box row (Perspective), this text at the end: "Learn about effective White Paper Promotion." Include this hyperlink and have it open in a new window. See attached image.

4) Within user profile, the "Advertising" and "Newsletter Distribution" forms show the form's name twice on this page. Please remove the hyperlinked blue names and the thin gray lines (see image).

5) Link the "Sign in to google docs" button to open in a new window

**Comment by saurabhd** [comment]
Hello Greg,
1. For users with role "PR Activity", this page has a Google Doc iFrame. Sometimes the user is not logged into Google Docs and the iFrame is blank. If blank, can we show a text message somewhere "No Google Doc visible? Please sign in to Google Docs".
   >> We cannot display message as we are fetching content from iFrame.

Thanks!
