### ISSUE TITLE
New edits

### ISSUE THREAD

**Issue by gatsby8870** [snehal-addweb/Mortgagespeak#50]
Hello. Here is new work to be performed preferably in the order below:
1. On Upload page, edit text in lower gray row to state: "Upload | Learn about effective White Paper promotion." (hyperlink effective White Paper promotion and open in new window.) to document [here](http://mortgage.saurabhdhariwal.com/effective-promotion-white-paper); see image; Also remove the identical text from the second checkbox in the form itself (it is now a duplication); Upload-Page-White-Papers-link.png
2. On Perspective page, hyperlink "White Papers" in lower gray row to same document as above; see image: Perspectives-page-White-Papers-link.png; open in new window as well.
3. On pop up tab, add "View on web" button (see attached); no color change onclick; Opens content in new window just like headline from pop up; see "View on web.png"
4. On "My Page" and for user roles "PR Activity", edit "PR Activity" text link to "RGA Activity"
5. Change public user role to show the gray "Company" row in the center content with links to any listed company. I am making this open to all users: logged in and non-logged in.
6. Show the link "+ Follow" in the lower gray row and the "Save" icon (center content) to all public users but require log in/registration onclick to perform function.
7. Edit text "Copy to Clipboard" shown on icon mouseover in center table to state "Copy link to clipboard".
8. In "My Page" > lower gray row, edit link text "Tracked News" to state "Tracked Topics"
9. In user profiles, remove the bottom section titled "Tracked Companies". I do not wish to show the user the companies they are and can be tracking.

![upload-page-white-papers-link](https://cloud.githubusercontent.com/assets/18587752/15382365/5c19d3e4-1d4f-11e6-9a5f-6fe843c1fe80.png)

![perspectives-page-white-papers-link](https://cloud.githubusercontent.com/assets/18587752/15382392/9d1d763e-1d4f-11e6-97de-4bca0f9f88d4.png)

![view-on-web](https://cloud.githubusercontent.com/assets/18587752/15382414/e6ac8164-1d4f-11e6-937c-edd447f7c14f.png)

**Comment by gatsby8870** [comment]
Question: How can I edit the text in the lower gray rows in the center of the page? For example, the new "Company Newsroom" is using the same text as the "News" page's text and I would like to change it.

Thank you!

**Comment by roshni-addweb** [comment]
Hello Greg,

Question: How can I edit the text in the lower gray rows in the center of the page? For example, the new "Company Newsroom" is using the same text as the "News" page's text and I would like to change it.

=> This is technical stuff, provide me the changes and I can implement it.

**Comment by Krina-Addweb** [comment]
Hello Greg,

All the points are done except point 6, please check it over mortgage.saurabhdhariwal.com/.

Thanks

**Comment by gatsby8870** [comment]
Please edit the "P" in "Promotion" (in the lower gray bar) to be lower case:

"Upload | Learn about effective White Paper promotion."

http://mortgage.saurabhdhariwal.com/upload

**Comment by gatsby8870** [comment]
Hello, item #5 does not appear to be done.
1. Change public user role to show the gray "Company" row in the center content with links to any listed company. I am making this open to all users: logged in and non-logged in.

Viewing this link, I do not see the word's "Company: Fannie Mae" in the center content". This company content should be visable to all users (logged in and not logged in)

e.g. http://mortgage.saurabhdhariwal.com/fannie-mae

**Comment by Krina-Addweb** [comment]
Both the Points are done over mortgage.saurabhdhariwal.com::

1) Change public user role to show the gray "Company" row in the center content with links to any listed company. I am making this open to all users: logged in and non-logged in.

Viewing this link, I do not see the word's "Company: Fannie Mae" in the center content". This company content should be visible to all users (logged in and not logged in)

2) Please edit the "P" in "Promotion" (in the lower gray bar) to be lower case:
"Upload | Learn about effective White Paper promotion."
