### ISSUE TITLE
Upload and new items

### ISSUE THREAD

**Issue by gatsby8870** [snehal-addweb/Mortgagespeak#51]
Hello, I will be giving a tour this week so I'd like the site uploaded first. Here are some edits/items:

Edits:
1. Upload site to my server
2. Login redirect not working. Seems to redirect to user profile page. See user Beata. Log in as admin, check Beata credentials then try to log in as Beata using those credentials to see issue. Same for user Rick.
3. Rename text on lower gray row on these pages:

(News): News Headlines
(Press Releases): Press Releases
(Perspectives): White Papers and Thought Leadership (keep text's existing hyperlink)
(Company Newsrooms): Company Newsrooms
1. Site Formatting and Browser Issues -
   Welcome Page on iPad is all jumbled

Safari: page "Company Newsrooms" has incorrect search bar formatting; it goes the full length in this browser and should not; see attached

**Comment by gatsby8870** [comment]
Log in not working. As outlined in #2, check the credentials for user Beata then attempt to log in as that user. It does not work yet it is marked as done.

The Safari issue regarding the search bar being too long on the "Company Newsrooms" page is not done.

**Comment by roshni-addweb** [comment]
Hello Greg,
1. Log in not working. As outlined in #2, check the credentials for user Beata then attempt to log in as that user. It does not work yet it is marked as done.
   => Previously, on Register it will be redirecting to - User Profile Page and on Login it will be redirecting to - My Page Tracked news. But now it will be redirect to User Profile Edit Page.

Please let me know if there is any further changes.
1. The Safari issue regarding the search bar being too long on the "Company Newsrooms" page is not done.
   => It seems like OS related issue and won't be fixed.

**Comment by gatsby8870** [comment]
1a. The redirect edit you performed (#1) is incorrect. I did not ask for a change in redirect. Update the redirect so both the Login and Registration redirect to the user's "My Page" upon successful access.

1b. Also regarding this, the larger issue is the login credentials often do not work. For example, view as admin the credentials for user "Beata" and then attempt to use those credentials to log in. It does not work. Why?

**Comment by gatsby8870** [comment]
Hello, please perform these edits:

**-Daily Newsletter edits-**
1. Show user first name in newsletter
2. Update top header to as shown in image
3. Add "Sponsor" line, text and link as shown.

**Notes**: I updated and attached the html code but it excludes the top header work. Just use code and perform top header work

[Daily.Newsletter.text.txt](https://github.com/snehal-addweb/Mortgagespeak/files/317678/Daily.Newsletter.text.txt)

**--Other edits--**
1. When enabled for users with this role ("Statistics") and no statistics are found (My Page > Statistics), the green system message says "No Newsletter Assigned"; Change to "No statistics at this time")

**Comment by gatsby8870** [comment]
The Daily Newsletter code needs its top header to look like this image (attached; remove old logo, use new image of house + name, etc.)

Additionally, the first line: Dear (user first name): needs to show the user's first name not the text "(user first name)"

![daily-newsletter](https://cloud.githubusercontent.com/assets/18587752/16129179/6494a536-33c9-11e6-9b66-0de101306aaa.jpg)

**Comment by Krina-Addweb** [comment]
Hello Greg,

The Daily Newsletter code needs its top header to look like this image (attached; remove old logo, use new image of house + name, etc.)
=> Done

Notes :
1. On creation of the Newsletter you will see #username# but it will be replaced in emails 
2. If User is registered and subscribed to "Daily Newsletter"  "#username#" will be replaced by "User's First name" for e.g (johnny.8)
3. If User is not registered and subscribed to "Daily Newsletter"  "#username#" will be replaced by "User's email address" for e.g (johnnyharpertesting1@gmail.com)
   ![non registered and subscribed user](https://cloud.githubusercontent.com/assets/14847553/16148380/d236fbb0-34a6-11e6-93a1-efb58760ef63.png)
   ![registered and subscribed user](https://cloud.githubusercontent.com/assets/14847553/16148381/d23bf20a-34a6-11e6-9e13-d34b8f15b2cb.png)
