### ISSUE TITLE
Site edits

### ISSUE THREAD

**Issue by gatsby8870** [snehal-addweb/Mortgagespeak#52]
Hello, kindly perform these edits:
1. Make Search bars within the News, Press Releases and Pespective pages the same search bar width as on the one on the News page; the bar on the Perspectives page is definitely not wide enough
2. Just hyperlink only the words "White Papers" in the text "White Papers and Thought Leadership"  on the Perspectives page lower gray row. Not the full sentence "White Papers and Thought Leadership".
3. When uploading the new site, keep the existing site online somewhere so I can access its content for manual copying/pasting into new site.

Thank you.

**Comment by gatsby8870** [comment]
The search bar on the Perspectives page is not done. http://mortgage.saurabhdhariwal.com/perspectives

**Comment by roshni-addweb** [comment]
Hello Greg,

That's working fine. Please check on http://162.243.55.198/perspectives

**Comment by gatsby8870** [comment]
The issue is the search bar **length**.

See issue statement:
Make Search bars within the News, Press Releases and Pespective pages the same search bar width as on the one on the News page; **the bar on the Perspectives page is definitely not wide enough**
