### ISSUE TITLE
Edit items

### ISSUE THREAD

**Issue by gatsby8870** [snehal-addweb/Mortgagespeak#54]
1. On My Page > Tracked Topics:

In the center content table area, remove the gray text/row stating "Companies:"
1. On My Page > Tracked Companies

In the center content table area, remove the gray text/row stating "Mortgage Topic:"

See attached two images for reference

![image](https://cloud.githubusercontent.com/assets/18587752/15917812/9c2c346e-2dc5-11e6-9c59-48389f80b16a.png)
![image](https://cloud.githubusercontent.com/assets/18587752/15917813/9c4370a2-2dc5-11e6-8b19-72249539e627.png)

**Comment by roshni-addweb** [comment]
Hello Greg,

Please let me know should i have to make the respective changes over its inner pages also? i.e. For Companies (http://162.243.55.198/guild-mortgage-co) & For Tracked Topics (http://162.243.55.198/fhahud).

**Comment by Krina-Addweb** [comment]
Hello Greg,
Please check these changes over live site (http://162.243.55.198/).
Thanks
