### ISSUE TITLE
Internet 11 Compatibility Issue and Newsletter links

### ISSUE THREAD

**Issue by gatsby8870** [snehal-addweb/Mortgagespeak#57]
1. When viewed in IE 11, my site's top left corner (where images and date+ info are), the site is misaligned. Image attached.
2. For "Client" newsletter content links (e.g. "headlines"), these links should open the location of the source content and not redirect to my site. Client newsletters, as part of their service with me, get a newsletter providing direct links to the content. In some rare cases, that content will be hosted at my site (e.g. Press Releases and Perspectives). This edit is critical.

![ie---11-compatibilty-issue-on-display](https://cloud.githubusercontent.com/assets/18587752/16284100/2a5efeea-3895-11e6-857c-74fc2a0ca114.png)

**Comment by Krina-Addweb** [comment]
Hello Greg ,
Following both points were done , please check it over mortgagespeak.com
1) When viewed in IE 11, my site's top left corner (where images and date+ info are), the site is misaligned. Image attached. >> Done
2 )For "Client" newsletter content links (e.g. "headlines"), these links should open the location of the source content and not redirect to my site. Client newsletters, as part of their service with me, get a newsletter providing direct links to the content. In some rare cases, that content will be hosted at my site (e.g. Press Releases and Perspectives). This edit is critical. >> Done
