### ISSUE TITLE
Social Networking urls and Client own missing in newsletter

### ISSUE THREAD

**Issue by gatsby8870** [snehal-addweb/Mortgagespeak#58]
**1. "Read More" button with link**

For content where the URL field is populated by me via ".../node/add/alpha-content", show a "Read More" button (as attached). Link button to the URL as entered into the field (opens in new window).

For content where the URL field is not populated by me, do not show the "Read More" button.

**2. Social Networking links via Pop Excerpt Tab**
The links shared by the social networking buttons in the main table rows are different than the links shared via the pop up Excerpt window's social networking buttons.

Leave the links in the main table alone.
Change the links in the pop up excerpt tab to the same as the links used in the main table's social networking buttons except do not change the "View on Web" button and the Headline URL.

**3. Client pw not showing in generated client newsletter.**
For user "Rick" with distribution list RGA Public Relations, pw is not showing in the blue section 

![image](https://cloud.githubusercontent.com/assets/18587752/16511595/8340bd0e-3f17-11e6-90e5-fe84f3341ad0.png)

**Comment by roshni-addweb** [comment]
Hello Greg,

1 "Read More" button with link

Whenever content has external link, we redirect users to this external link when they click on content. So we don't need read more button on such content. 

We have added Read more button on alpha content pages. You can check this from admin backend (Working on button css).

3 Client pw not showing in generated client newsletter.
For user "Rick" with distribution list RGA Public Relations, pw is not showing in the blue section

=> Previously passwords were set for particular username only(Forsythe Appraisals, Valocity, RGA Public Relations, Platinum, etc). Now password is set for whichever user is selected from dropdown.

**Comment by gatsby8870** [comment]
Hello.

My goal is to socially share the "landing page" so the "Read More" button was important to have on this page as users can then go from the landing page to the full content.

I am looking to generate more Google adsense revenue by sharing content but the links to external content bypass my site. Hence I wanted the read more button.

Perhaps I am missing something and will check now.

Get Outlook for Androidhttps://aka.ms/ghei36

On Mon, Jul 4, 2016 at 9:41 AM -0500, "roshni-addweb" <notifications@github.com<mailto:notifications@github.com>> wrote:

Hello Greg,

1 "Read More" button with link

Whenever content has external link, we redirect users to this external link when they click on content. So we don't need read more button on such content.

We have added Read more button on alpha content pages. You can check this from admin backend.

3 Client pw not showing in generated client newsletter.
For user "Rick" with distribution list RGA Public Relations, pw is not showing in the blue section

=> Previously passwords were set for particular username only(Forsythe Appraisals, Valocity, RGA Public Relations, Platinum, etc). Now password is set for whichever user is selected from dropdown

##

**Comment by gatsby8870** [comment]
Hi, I thought I'd share a little more about this. 

My goal is to increase my Google AdSense revenue. I can do this by sharing the content I enter into my site. But most (not all) content is hosted elsewhere so sharing it shares the source content link and not my site so I don't make any revenue. 

By adding the Read More button as requested and updating the shared links as I detailed, I can make more money.

Thank you.

**Comment by Krina-Addweb** [comment]
Hello Greg,

Please review 2nd point over live site.

Also please check above mentioned changes for 1st point  over live site.

Thanks

**Comment by gatsby8870** [comment]
Hello, please make this single change:

In the pop up tab, have the "View on web" button link to the same URL used as the hyperlinked headline text.

This change should not affect any of the other social buttons.

Thank you.

**Comment by Krina-Addweb** [comment]
Hello Greg,
Please review & check above given change over live site.
Thanks
