### ISSUE TITLE
Unload module

### ISSUE THREAD

**Issue by gatsby8870** [snehal-addweb/Mortgagespeak#59]
Hi. A client of mine forgot their password and locked themselves out. I couldn't unlock their account because it's a 5 hour wait. 

I found this module as a possible solution but couldn't install it. 

Could you install this module?  https://www.drupal.org/project/flood_unblock

Additionally, it was frustrating and strange that in order to reset your password, you get a link that requires you to enter your old password. If the user knew this, they wouldn't need to reset it. 

Is there another option?

**Comment by roshni-addweb** [comment]
Hello Greg,

I have added flood control and flood unblock module. From flood control you can adjust lock time period.
Configuration links:
For Unblock users : http://mortgagespeak.com/admin/config/system/flood-unblock
For Lock time : http://mortgagespeak.com/admin/config/system/flood-control

Please let me know if you have any questions.

**Comment by gatsby8870** [comment]
Could you please install this module to offer a new way to reset a user's password? The current process requires them to enter their password even though the forgot it. 

https://www.drupal.org/project/simple_pass_reset

**Comment by roshni-addweb** [comment]
I have added another module. Please check.
