### ISSUE TITLE
Small edits

### ISSUE THREAD

**Issue by gatsby8870** [snehal-addweb/Mortgagespeak#61]
Hello, please :
1. Increase file size upload limit to 8MB with DigitalOcean; Drupal setting already changed: https://www.drupal.org/node/2608620
2. Create RSS feed for my press release page: http://www.mortgagespeak.com/press-releases

Thank you!

**Comment by roshni-addweb** [comment]
Hello Greg, 
1. Increase file size upload limit to 8MB with DigitalOcean; Drupal setting already changed
   => Done
2. Create RSS feed for my press release page
   => Url for feeds is (http://mortgagespeak.com/press-feeds) 

Please let me know if you have any queries.

**Comment by gatsby8870** [comment]
Hi, regarding #2, it doesn't appear to work for my client.

He wrote:

"Thanks, Greg.

The links to the item are relative links that won't work when sent to another site. See here: http://www.gkexaminer.com/2016/07/ron-ahlensdorf-jr-on-brand-focus/

Getting close though! Thanks for your hard work."

**Comment by roshni-addweb** [comment]
Hello,

I made changes to fix this. Please check this by clearing cache and updating feeds again on your client's site.
