### ISSUE TITLE
Mortgage Solutions Newsletter 

### ISSUE THREAD

**Issue by gatsby8870** [snehal-addweb/Mortgagespeak#62]
Hello, I am unable to send the newsletter for user FAF.

This is my largest client and I get the following error.

Please resolve ASAP. I have a meeting with them today. Also please be careful not to send any unspent newsletters. I don't want them flooded with newsletter.

Thank you!
## 

Tried to Send FAF newsletter after updating my SMTP module with updated GMail credentials. Worked for all but not FAF. Got this:

An AJAX HTTP error occurred. HTTP Result Code: 200 Debugging information follows. Path: /batch?id=834&op=do StatusText: OK ResponseText: SMTP Error: Could not authenticate. {"status":true,"percentage":"33","message":"Completed 2 of 6.\u003Cbr \/\u003E"}

**Comment by roshni-addweb** [comment]
Hello,

I made some changes and checked using "Test" Newsletter. Please check and let me know if you are facing any issue.

NOTE : Please don't change name of Mortgage Solutions "News Intelligence" and  Daily Newsletter in Newsletter categories.

**Comment by gatsby8870** [comment]
Hello.

The "Test" newsletter went through successfully. I am unsure if this resolves the newsletter for user "FAF" b/c my newsletters to other clients EXCEPT "FAF" went through fine. It was only FAF.

I can't test without sending it live or removing all email addresses from the distribution list and adding only myself. I am close enough to sending it live so I will just try it that way.

Thank you for your promptness! I will reply with results.

Thank you again.

**Comment by gatsby8870** [comment]
Hi, it looks like all newsletters, including for user "FAF", were sent successfully.

I will speak with them today but it looks good from here.

Thank you again!
