### ISSUE TITLE
Quotes access

### ISSUE THREAD

**Issue by gatsby8870** [snehal-addweb/Mortgagespeak#63]
On my home page, there are quotes that show next to my large ad. Some of these quotes are mispelled.

How can i access these quotes? I do not have ftp access. 

Note: tomorrow morning I am issuing a press release so there will be more visitors. 

Thank you!

**Comment by gatsby8870** [comment]
Perhaps I could just submit a new file as the easiest solution?

**Comment by saurabhd** [comment]
Yes, we can submit new file as an easiest solution. Please provide me the updated file and I would upload it.

**Comment by gatsby8870** [comment]
Ok, great. I fell asleep so I'm heading home to do this now. You should have it in hour.

Thank you again!

Get Outlook for Androidhttps://aka.ms/ghei36

On Wed, Aug 3, 2016 at 1:07 AM -0500, "Saurabh Dhariwal" <notifications@github.com<mailto:notifications@github.com>> wrote:

Yes, we can submit new file as an easiest solution. Please provide me the updated file and I would upload it.

##

**Comment by gatsby8870** [comment]
Hello!

Here is the updated quotes file in the format you previously requested.

Please let me know of any troubles and thank you for doing this! My press release goes out this morning. Big morning for me!

1 attachment
[Quotes Revised File 1.txt](https://github.com/snehal-addweb/Mortgagespeak/files/399227/Quotes.Revised.File.1.txt)

**Comment by Krina-Addweb** [comment]
Hello Greg,

Wish you luck for your press release!

We made the changes as per your given text file, please check the changes over live site.

Thanks!

**Comment by gatsby8870** [comment]
Thank you!
