### ISSUE TITLE
Log in issues yet again

### ISSUE THREAD

**Issue by gatsby8870** [snehal-addweb/Mortgagespeak#65]
I continue to have serious log in issues. I would like to 1). know and 2). resolve why the log in does not work consistently for some users.

Please follow these steps:
1. verify via admin log in user has these credentials
- un:   LBuser@firstam.com
- pw:   LBuser@firstam.comKcXNJR
1. Then try to log in with them.

It does not work in FF nor IE.

This is my largest client and an issue I've written about before.

Thank you.

**Comment by saurabhd** [comment]
Hey Greg, 

I am unable to replicate and find the root cause of this issue, tried all possible way out. Would still dig more and let you know. 

Thanks!

**Comment by gatsby8870** [comment]
Are you saying you can log into the site using this users credentials?

**Comment by gatsby8870** [comment]
I will try from another computer in a new location to test as well.

**Comment by saurabhd** [comment]
Ok

**Comment by gatsby8870** [comment]
I have not had any issues with the login credentials mentioned in this email. Was there any work done? Just interested in what the solution was...

**Comment by saurabhd** [comment]
Nop, we have not worked on anything on this piece.
