### ISSUE TITLE
FAF Newsletter send error again

### ISSUE THREAD

**Issue by gatsby8870** [snehal-addweb/Mortgagespeak#66]
Hello, I received the below error message when sending the FAF newsletter.

The perhaps only difference is the solution provided last tiem was done for the standard newsletter they get every day and not the "weekly" newsletter I send.

I am unsure but I received this error below when sending their "Weekly" newsletter (user "FAF"; newsletter "Mortgage Solutions")
## 

An error has occurred.
Please continue to the error page

An AJAX HTTP error occurred. HTTP Result Code: 200 Debugging information follows. Path: /batch?id=1159&op=do StatusText: OK ResponseText: The following From address failed: newsletter@mortgagespeak.com SMTP Error: Could not authenticate. {"status":true,"percentage":"67","message":"Completed 4 of 6.\u003Cbr \/\u003E"}

**Comment by saurabhd** [comment]
It seems its an issue of Drupal module i.e 'Simple News'. We have currently set mails over cron run [ as per our old site ]. So, you need to run cron before sending emails. 

Please check and let us know if any concerns for the same. 

Thanks!
