### ISSUE TITLE
Newsletter

### ISSUE THREAD

**Issue by gatsby8870** [snehal-addweb/Mortgagespeak#67]
Hello, would you please perform these edits to the "Client Newsletter"?

**Icons:**
1. Please replace the light blue icon displayed for "news" topics (displayed as "Tracked Topics" currently) to the updated blue attached image?
2. Please display a unique purple icon for headlines assigned as "Press Releases". Currently, press releases and perspectives use the same light blue "Track Topics" listed above. I would like this unique purple icon. It can be used for both "Press Releases" and "Perspective" content.
3. When the purple icon is displayed, the accomplaying gray text now stating "Press Releases", can we simply edit this to say "Press Release" (no "s"). It makes more sense.
4. Are newsletters statistics (e.g. open rate) being recorded? I went to the statistics page for the newsletter and there was nothing. It also always says "Newsletter category format has not been set to HTML. There will be no statistics recorded for this newsletter." But upon research, it IS set to html, I believe.

see: http://www.mortgagespeak.com/admin/content/simplenews/statistics

Please see the attached images.

Thank you!

![newsletter-new-icons-look](https://cloud.githubusercontent.com/assets/18587752/17799607/96c80aa2-65a1-11e6-82b9-b667eb134448.png)
![newsletter-press-release-and-perspective-icon](https://cloud.githubusercontent.com/assets/18587752/17799609/96ca9ab0-65a1-11e6-8e90-dcc0ae3bd0ec.png)
![newsletter-tracked-news-icon](https://cloud.githubusercontent.com/assets/18587752/17799608/96caa0aa-65a1-11e6-8988-6fbb66ed053a.png)

**Comment by gatsby8870** [comment]
1. Kindly also "top-align" the logos so when viewed on mobile (e.g. cell phone), the logos are moved "up" instead of centered aligned. It just looks better. See attached purple arrow examples...

![newsletter-logos-to-be-moved-up](https://cloud.githubusercontent.com/assets/18587752/17864808/3ec00500-6865-11e6-813e-bc247c9c0220.png)

**Comment by Krina-Addweb** [comment]
Hello Greg,
Above Mentioned changes are done. Please Check.
Can you please provide high resolution images for "Press Release" & "Tracked News" as is looks blurry.
Thanks.

**Comment by gatsby8870** [comment]
Hello, thank you for your help.

But I do not see this part of the issue addressed:
1. Are newsletters statistics (e.g. open rate) being recorded? I went to the statistics page for the newsletter and there was nothing. It also always says "Newsletter category format has not been set to HTML. There will be no statistics recorded for this newsletter." But upon research, it IS set to html, I believe.

Thank you!

**Comment by roshni-addweb** [comment]
Hello Greg,

Above Message will be seen only when there is no category assigned to the Newsletter. Once you assign any category then the message will be disappear. It will not affect statistics.

Thanks.

**Comment by gatsby8870** [comment]
Thank you.

Can you provide me a link to where I can see the statistics for these daily newsletters?

From my research, the statistics page was blank for all newsletters all the time.

One of the reasons why I ask is my largest client is wanting to know who is and who is not using the service they are paying me for. I would like to be proactive with knowing this so I can reduce those numbers by monitoring the click rates, usage, etc on the user level.

Thank you.

**Comment by roshni-addweb** [comment]
Hello Greg,

Can you provide me a link to where I can see the statistics for these daily newsletters?
=> This stats won't be displayed on our My page "Statistics" tab as it was coded for only Alpha content links. To view Stats for Daily Newsletter you need to follow below steps.
1. Click on Newsletter(From http://mortgagespeak.com/admin/content/simplenews).
2. Goto Statistics tab, there you will see Statistics for particular Newsletter then click on "Newsletter clicks" tab and there you will see all clicks of respective Newsletter.

PFA screenshot for the same.

Please let me know if you have any queries for the same.

![daily newsletter stats](https://cloud.githubusercontent.com/assets/14847556/17959758/0c9ee2c8-6ac0-11e6-9465-dbed79c36f8f.png)

Thanks
