### ISSUE TITLE
Estimate

### ISSUE THREAD

**Issue by gatsby8870** [snehal-addweb/Mortgagespeak#68]
**OVERVIEW**: Deliver my clients a "Recommended list" of headlines to share on LinkedIN via
1. Newsletter
2. Web page

**Newsletter**:
1. Use new code provided to update client NI newsletter. There are links updates, etc.
2. The article count in the blue box area pulls from the new web page's "Articles Available" gray box
3. My new code is missing the lower "LinkedIN recommended" checkmark image and right text share links. I attached an image as an example.
4. Increase the character length for both headline and gray text since the white space has been in increased/gray background decreased

_Notes_:
1. Articles are designated as "LinkedIN Recommended" when radio-box "Recommended for LinkedIN" is clicked "Yes" in content creation
2. This also causes the checkmark image to bedisplayed in the newsletter
3. The content that is shared via the newsletter's share links is the content's landing page at my site (example and not source content).
4. Clicking the checkmark image also acts as the LinkedIN Share link
5. Increase the character count for the headline and lower gray rows. I reduced the outer gray margin to provide more room.

**Web page**:
1. Use this page. The newsletter is coded to link here.
2. This page unites content designated as "Recommended for LinkedIN"
3. Offer 1 filter titled "Search By Topic" using the news topic taxonomies; Default selection is "All news topics", then individual taxonomy terms.
4. This filter shows "LinkedIN recommended" content by topic.
5. Replace the 14x14 pixel LinkedIN share icon in the tables rows AND pop up Except tab with the wider button in the attached image. Ok to expand Excerpt tab as needed.

_Notes_:
1. This new web page does not require log in/registration
2. Rename center nav bar tab "Upload Content" to "LinkedIN Articles"; move this tab to 2nd position from left

**Comment by saurabhd** [comment]
Hello Greg,

Quick queries:

1. I think images are missing. Can you please share all images?

2. Shared By User: (change from "Search By User"): shows email addresses
> Here, which email address are you planning to show?

Can provide you estimates once I get to see the images.

**Comment by gatsby8870** [comment]
Hi, here are the images. Please let me know if they did not come through.

Thank you!

________________________________

**Comment by saurabhd** [comment]
Unable to get it Greg. Can't see any images attached.  

I think it would be great if you could send all images via mail please.

**Comment by saurabhd** [comment]
![image](https://cloud.githubusercontent.com/assets/2010385/19115123/613dfc90-8b2e-11e6-9a77-b5ad7a4b3817.png)

**Comment by saurabhd** [comment]
Reviewed the edited comment and estimates would be 40 working hours.

**Comment by gatsby8870** [comment]
Here are updates:

1. The new "Share on LinkedIN" button shown in image also needs to go within the Excerpt tab; Increase tab's width as needed.
2. Update/increase character headline and gray text character length in newsletter b/c the white space is increased b/c I reduced the gray background's margin.
3. Updated NI newsletter code to use is below (minor color and text changes)

<p><span style="color: #ffffff;">&nbsp;Uniting your client, competitor and prospect news.</span></p>
<table class="main-outer-table" style="width: 100%; max-width: 800px; margin-top: 50px; border-spacing: 0; border-collapse: collapse; border: none;" align="center">
<tbody>
<tr class="header-section" style="background: #2e8cf0;">
<td style="padding: 0; margin: 0; border: 1px solid #2e8cf0; line-height: normal;">
<table style="width: 100%; margin: 5px auto; border-spacing: 0; border-collapse: collapse; padding: 0; background-color: #2e8cf0; border: 1px solid #2e8cf0;" cellpadding="10">
<tbody>
<tr>
<td style="padding: 0px 30px; margin: 0px; line-height: normal;">
<table class="header-table" style="margin: 0px auto; width: 100%; border-collapse: collapse; padding: 0; border: none; line-height: normal;" align="center">
<tbody>
<tr>
<td style="padding: 7px 0; margin: 0; line-height: normal;" width="55"><a style="text-decoration: none;" href="http://mortgagespeak.com"><img style="vertical-align: middle;" src="http://www.mortgagespeak.com/sites/default/files/ms.png" alt="" /></a></td>
<td style="padding: 7px 0 0; margin: 0; vertical-align: top;">
<table style="padding: 0; margin: 0; border-spacing: 0; border-collapse: collapse; width: 100%; border: none;">
<tbody>
<tr>
<td style="padding: 0; margin: 0; letter-spacing: 1px; font-family: arial; color: #ffffff; font-size: 14pt; font-weight: bold;"><span>Newsletter</span></td>
</tr>
<tr>
<td style="padding: 7px 0 0; vertical-align: bottom; margin: 0; line-height: normal; letter-spacing: 1px; font-family: arial; font-size: 10pt; color: #ffffff;">by MortgageSpeak</td>
</tr>
</tbody>
</table>
</td>
</tr>
</tbody>
</table>
</td>
</tr>
</tbody>
</table>
</td>
</tr>
<tr class="body-section" style="background: #F4F4F4;">
<td style="padding: 0; border: 1px solid #bebfb9;">
<table class="main-table" style="width: 100%; margin: 0px auto; border-collapse: collapse; padding: 5px; border: none; background-color: #f4f4f4;" align="center">
<tbody>
<tr>
<td style="border: 0px none; border-collapse: collapse; border-spacing: 0px; padding: 0 40px;">&nbsp;</td>
</tr>
<tr>
<td style="border: 0px none; border-collapse: collapse; border-spacing: 0px; padding: 0px 10px;">
<table style="border-radius: 5px 5px 0 0; padding: 0; border-spacing: 0; border-collapse: collapse; background-color: #ffffff; border: none; margin: 0 auto; width: 100%;" align="center">
<tbody>
<tr>
<td style="padding: 0 20px;">
<div style="width: 100%; border-top: 2px solid #ffffff;">&nbsp;</div>
</td>
</tr>
<tr>
<td style="padding: 0 20px 15px 20px;">
<table style="width: 100%; font-size: 13px; color: #666666; border: 0px solid #fff; border-collapse: collapse; border-spacing: 0; box-sizing: border-box; border-style: none; margin: 0;">
<tbody>
<tr>
<td style="padding: 5px 3px; color: #000000;"><span style="font-size: small; font-family: arial, helvetica, sans-serif;"><strong style="font-family: arial;">Headlines</strong></span></td>
<td style="color: #000000; padding: 5px 3px; text-align: center;"><span style="font-size: small; font-family: arial, helvetica, sans-serif;"><strong style="font-family: arial;">Today</strong></span></td>
<td style="color: #000000; padding: 5px 3px;" align="center"><span style="font-size: small; font-family: arial, helvetica, sans-serif;"><strong style="font-family: arial;">Y.T.D.</strong></span></td>
</tr>
<tr style="background: url('initial') #fefce5;">
<td style="padding: 7px 3px; text-indent: 0px; font-family: arial;"><span style="font-size: small; font-family: arial, helvetica, sans-serif; color: #333333;">&nbsp; LinkedIN Recommendations</span></td>
<td style="padding: 7px 3px; text-align: center; font-family: arial;"><span style="font-size: small; font-family: arial, helvetica, sans-serif; color: #333333;">2</span></td>
<td style="padding: 7px 3px; text-align: center; font-family: arial;"><span style="font-size: small; font-family: arial, helvetica, sans-serif; color: #333333;">25</span></td>
</tr>
<tr>
<td style="padding: 5px 3px; text-indent: 0px; font-family: arial;"><span style="font-size: small; font-family: arial, helvetica, sans-serif; color: #333333;">&nbsp; Tracked Companies</span></td>
<td style="padding: 5px 3px; text-align: center; font-family: arial;"><span style="font-size: small; font-family: arial, helvetica, sans-serif; color: #333333;">2</span></td>
<td style="padding: 5px 3px; text-align: center; font-family: arial;"><span style="font-size: small; font-family: arial, helvetica, sans-serif; color: #333333;">25</span></td>
</tr>
<tr>
<td style="padding: 5px 3px; text-indent: 0px; font-family: arial;"><span style="font-size: small; font-family: arial, helvetica, sans-serif; color: #333333;">&nbsp; Tracked Sectors</span></td>
<td style="padding: 5px 3px; text-align: center; font-family: arial;"><span style="font-size: small; font-family: arial, helvetica, sans-serif; color: #333333;">2</span></td>
<td style="padding: 5px 3px; text-align: center; font-family: arial;"><span style="font-size: small; font-family: arial, helvetica, sans-serif; color: #333333;">25</span></td>
</tr>
<tr>
<td style="padding: 5px 3px; text-indent: 0px; font-family: arial;"><span style="font-size: small; font-family: arial, helvetica, sans-serif; color: #333333;">&nbsp; <strong>Total</strong></span></td>
<td style="padding: 5px 3px; text-align: center; font-family: arial;"><span style="color: #333333;"><strong><span style="font-size: small; font-family: arial, helvetica, sans-serif;">2</span></strong></span></td>
<td style="padding: 5px 3px; text-align: center; font-family: arial;"><span style="color: #333333;"><strong><span style="font-size: small; font-family: arial, helvetica, sans-serif;">25</span></strong></span></td>
</tr>
<tr>
<td style="padding: 5px 3px; text-indent: 0px; font-family: arial;">&nbsp;</td>
<td style="padding: 5px 3px; text-align: center; font-family: arial;">&nbsp;</td>
<td style="padding: 5px 3px; text-align: center; font-family: arial;">&nbsp;</td>
</tr>
</tbody>
</table>
</td>
</tr>
<tr>
<td style="padding: 0 20px 15px 20px;">
<table style="width: 100%; font-size: 13px; color: #666666; border: 0px solid #fff; border-collapse: collapse; border-spacing: 0; box-sizing: border-box; border-style: none; margin: 0; border-color: #ffffff; border-width: 0px;">
<tbody>
<tr>
<td style="padding: 10px; color: #000000; background-color: #edfcf2;">
<p><span style="font-size: small; font-family: arial, helvetica, sans-serif; color: #222222;"><span style="color: #0000ff;">Log in to here </span>to view historical "Tracked Company" news:</span></p>
<ul>
<li><span style="font-size: small; font-family: arial, helvetica, sans-serif; color: #222222;">username: &nbsp;<span style="background-color: #e7fbed;">mercuryvmp</span></span></li>
<li><span style="font-size: small; font-family: arial, helvetica, sans-serif; color: #222222;">password: &nbsp;mercuryvmp@1234</span></li>
</ul>
</td>
</tr>
<tr>
<td style="padding: 5px 3px; color: #000000;">&nbsp;</td>
</tr>
<tr>
<td style="padding: 0 20px 0 20px;">
<div style="width: 100%; border-top: 2px solid #F07A22;">&nbsp;</div>
</td>
</tr>
</tbody>
</table>
</td>
</tr>
</tbody>
</table>
</td>
</tr>
<tr>
<td style="border-spacing: 0px; border-collapse: collapse; width: 100%; padding: 0px 10px;">
<table style="border-radius: 0 0 5px 5px; padding: 0; border-spacing: 0; border-collapse: collapse; background-color: #fff; border: none; margin: 0 auto; width: 100%;" align="center">
<tbody>
<tr class="News-intelligence" style="width: 100%;">
<td style="font-family: arial; font-size: 13px; padding: 10px 20px 0 20px; width: 100%; line-height: normal;">
<table style="width: 100%; font-size: 13px; color: #666666; border-width: 0px; border-image: initial; border-collapse: collapse; border-spacing: 0px; box-sizing: border-box; border-style: none; margin: 0px;" border="0" align="center">
<tbody>
<tr>
<td style="background-color: #f2f9fd;">&nbsp;</td>
</tr>
<tr>
<td style="background-color: #f2f9fd;">
<p style="text-align: center;"><span style="color: #808080; font-family: tahoma, arial, helvetica, sans-serif; font-size: small;"><strong>Grow your brand</strong> by sharing content:</span></p>
<p style="text-align: center;"><span style="font-family: tahoma, arial, helvetica, sans-serif; font-size: medium; color: #0000ff;"><strong><span style="text-decoration: underline;">50</span></strong>&nbsp;LinkedIN Recommendations</span></p>
</td>
</tr>
<tr>
<td style="background-color: #f2f9fd;">&nbsp;</td>
</tr>
</tbody>
</table>
</td>
</tr>
<tr class="News-intelligence" style="width: 100%;">
<td style="font-family: arial; font-size: 13px; padding: 10px 20px 0 20px; width: 100%; line-height: normal;">
<table style="width: 100%; font-size: 13px; color: #666666; border-width: 0px; border-image: initial; border-collapse: collapse; border-spacing: 0px; box-sizing: border-box; border-style: none; margin: 0px;" border="0" align="center">
<tbody>
<tr>
<td align="center" valign="middle">&nbsp;</td>
</tr>
</tbody>
</table>
</td>
</tr>
<tr>
<td style="width: 100%; padding: 10px 20px;"><span style="font-family: arial, helvetica, sans-serif; font-size: x-large; color: #ff6600;">Headlines &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <span style="font-size: small;"><span style="font-size: x-small;"><span style="color: #808080;">More:</span> &nbsp;&nbsp;</span><span style="color: #2e8cf0;">News</span>&nbsp;&nbsp;<span style="color: #808080;">|</span> &nbsp;<span style="color: #2e8cf0;">Press Releases</span></span><span style="font-size: small;"><br /></span></span></td>
</tr>
<tr>
<td style="width: 100%; padding: 10px 20px;">
<table style="margin: 0px auto; border-collapse: collapse; width: 100%; border: none;">
<tbody>
<tr>
<td style="width: 100%; border-top: 1px solid #e5e6e9; border-bottom: 1px solid #e5e6e9; padding: 10px;">
<table style="margin: 0px auto; border-collapse: collapse; width: 100%; border: none;">
<tbody>
<tr>
<td style="width: 50px; padding: 0 10px 0 0; vertical-align: top;" valign="top" height="50">
<div style="vertical-align: top; height: 50px; max-height: 50px; width: 100%;"><img style="width: 50px; height: 50px; vertical-align: top;" src="http://www.mortgagespeak.com/sites/default/files/Logo_1.png" alt="" width="50" height="50" /></div>
</td>
<td style="line-height: normal; vertical-align: top; text-align: left; width: 100%; max-width: 540px; padding: 0;">
<div style="vertical-align: top; color: #b8b8b8; font-family: arial; font-size: 10px; margin-bottom: 3px; width: 100%; max-width: 540px;"><span style="color: #999999;">Tracked Company</span></div>
<div style="display: block; color: #2e8cf0; font-size: 13px; text-decoration: none; font-family: arial; margin-bottom: 3px; width: 100%; max-width: 540px;"><a style="color: #2e8cf0; font-size: 13px; text-decoration: none; font-family: arial;" href="http://blog.lres.com/roi-of-the-right-amc-what-you-need-to-know" target="_blank">ROI of the Right AMC: What You Need to Know</a></div>
<div style="display: block; font-family: arial; font-size: 13px; color: #808080; width: 100%; max-width: 540px;">Where choosing the right AMC adds great value:&nbsp; There are six primary...</div>
</td>
</tr>
</tbody>
</table>
</td>
</tr>
<tr>
<td style="width: 100%; border-top: 1px solid #e5e6e9; border-bottom: 1px solid #e5e6e9; padding: 10px;">
<table style="margin: 0px auto; border-collapse: collapse; width: 100%; border: none;">
<tbody>
<tr>
<td style="width: 50px; padding: 0 10px 0 0; vertical-align: top;" valign="top" height="50">
<div style="vertical-align: top; height: 50px; max-height: 50px; width: 100%;"><img style="width: 50px; height: 50px; vertical-align: top;" src="http://www.mortgagespeak.com/sites/default/files/Logo2_17.png" alt="" width="50" height="50" /></div>
</td>
<td style="line-height: normal; vertical-align: top; text-align: left; width: 100%; max-width: 540px; padding: 0;">
<div style="vertical-align: top; color: #b8b8b8; font-family: arial; font-size: 10px; margin-bottom: 3px; width: 100%; max-width: 540px;"><span style="color: #999999;">Tracked Company</span></div>
<div style="display: block; color: #2e8cf0; font-size: 13px; text-decoration: none; font-family: arial; margin-bottom: 3px; width: 100%; max-width: 540px;"><a style="color: #2e8cf0; font-size: 13px; text-decoration: none; font-family: arial;" href="http://www.globaldms.com/blog/catch-up-w/-global-dms-in-booth-410-at-the-calyx-ascend-16-event" target="_blank">Catch Up w/ Global DMS in Booth 410 at the Calyx Ascend &rsquo;16 Event</a></div>
<div style="display: block; font-family: arial; font-size: 13px; color: #808080; width: 100%; max-width: 540px;">From October 5th&nbsp;through the 7th, our own Vladimir Bien-Aime (CEO), Jody...</div>
</td>
</tr>
</tbody>
</table>
</td>
</tr>
<tr>
<td style="width: 100%; border-top: 1px solid #e5e6e9; border-bottom: 1px solid #e5e6e9; padding: 10px;">
<table style="margin: 0px auto; border-collapse: collapse; width: 100%; border: none;">
<tbody>
<tr>
<td style="width: 50px; padding: 0 10px 0 0; vertical-align: top;" valign="top" height="50">
<div style="vertical-align: top; height: 50px; max-height: 50px; width: 100%;"><img style="width: 50px; height: 50px; vertical-align: top;" src="http://www.mortgagespeak.com/sites/default/files/Logo2_0.png" alt="" width="50" height="50" /></div>
</td>
<td style="line-height: normal; vertical-align: top; text-align: left; width: 100%; max-width: 540px; padding: 0;">
<div style="vertical-align: top; color: #b8b8b8; font-family: arial; font-size: 10px; margin-bottom: 3px; width: 100%; max-width: 540px;"><span style="color: #999999;">Tracked Company</span></div>
<div style="display: block; color: #2e8cf0; font-size: 13px; text-decoration: none; font-family: arial; margin-bottom: 3px; width: 100%; max-width: 540px;"><a style="color: #2e8cf0; font-size: 13px; text-decoration: none; font-family: arial;" href="http://www.corelogic.com/blog/authors/terry-theologides/2016/09/us-housing-policy-update-september-2016.aspx#.V-UyKTMrKVM" target="_blank">U.S. Housing Policy Update: September 2016</a></div>
<div style="display: block; font-family: arial; font-size: 13px; color: #808080; width: 100%; max-width: 540px;">The debate around Property Assessed Clean Energy (PACE) programs is heating u...</div>
</td>
</tr>
</tbody>
</table>
</td>
</tr>
<tr>
<td style="width: 100%; border-top: 1px solid #e5e6e9; border-bottom: 1px solid #e5e6e9; padding: 10px;">
<table style="margin: 0px auto; border-collapse: collapse; width: 100%; border: none;">
<tbody>
<tr>
<td style="width: 50px; padding: 0 10px 0 0; vertical-align: top;" valign="top" height="50">
<div style="vertical-align: top; height: 50px; max-height: 50px; width: 100%;"><img style="width: 50px; height: 50px; vertical-align: top;" src="http://www.mortgagespeak.com/sites/default/files/Logo2_0.png" alt="" width="50" height="50" /></div>
</td>
<td style="line-height: normal; vertical-align: top; text-align: left; width: 100%; max-width: 540px; padding: 0;">
<div style="vertical-align: top; color: #b8b8b8; font-family: arial; font-size: 10px; margin-bottom: 3px; width: 100%; max-width: 540px;"><span style="color: #999999;">Tracked Company</span></div>
<div style="display: block; color: #2e8cf0; font-size: 13px; text-decoration: none; font-family: arial; margin-bottom: 3px; width: 100%; max-width: 540px;"><a style="color: #2e8cf0; font-size: 13px; text-decoration: none; font-family: arial;" href="http://www.housingwire.com/blogs/1-rewired/post/38098-corelogic-economist-heres-a-current-snapshot-of-the-mortgage-credit-market" target="_blank">CoreLogic economist: Here's a current snapshot of the mortgage credit market</a></div>
<div style="display: block; font-family: arial; font-size: 13px; color: #808080; width: 100%; max-width: 540px;">Where are we in the credit cycle? Are there more &ldquo;bubbles&rdquo; (bonds, subprime a...</div>
</td>
</tr>
</tbody>
</table>
</td>
</tr>
<tr>
<td style="width: 100%; border-top: 1px solid #e5e6e9; border-bottom: 1px solid #e5e6e9; padding: 10px;">
<table style="margin: 0px auto; border-collapse: collapse; width: 100%; border: none;">
<tbody>
<tr>
<td style="width: 50px; padding: 0 10px 0 0; vertical-align: top;" valign="top" height="50">
<div style="vertical-align: top; height: 50px; max-height: 50px; width: 100%;"><img style="width: 50px; height: 50px; vertical-align: top;" src="http://www.mortgagespeak.com/sites/default/files/Logo2_0.png" alt="" width="50" height="50" /></div>
</td>
<td style="line-height: normal; vertical-align: top; text-align: left; width: 100%; max-width: 540px; padding: 0;">
<div style="vertical-align: top; color: #b8b8b8; font-family: arial; font-size: 10px; margin-bottom: 3px; width: 100%; max-width: 540px;"><span style="color: #999999;">Tracked Company</span></div>
<div style="display: block; color: #2e8cf0; font-size: 13px; text-decoration: none; font-family: arial; margin-bottom: 3px; width: 100%; max-width: 540px;"><a style="color: #2e8cf0; font-size: 13px; text-decoration: none; font-family: arial;" href="http://www.housingwire.com/articles/38106-mortgage-fraud-rising-most-in-low-downpayment-loans" target="_blank">Mortgage fraud rising most in low-downpayment loans</a></div>
<div style="display: block; font-family: arial; font-size: 13px; color: #808080; width: 100%; max-width: 540px;">&ldquo;A lot of the bigger fraud schemes don&rsquo;t get uncovered through traditional qu...</div>
</td>
</tr>
</tbody>
</table>
</td>
</tr>
<tr>
<td style="width: 100%; border-top: 1px solid #e5e6e9; border-bottom: 1px solid #e5e6e9; padding: 10px;">
<table style="margin: 0px auto; border-collapse: collapse; width: 100%; border: none;">
<tbody>
<tr>
<td style="width: 50px; padding: 0 10px 0 0; vertical-align: top;" valign="top" height="50">
<div style="vertical-align: top; height: 50px; max-height: 50px; width: 100%;"><img style="width: 50px; height: 50px; vertical-align: top;" src="http://www.mortgagespeak.com/sites/default/files/track_news.png" alt="" width="50" height="50" /></div>
</td>
<td style="line-height: normal; vertical-align: top; text-align: left; width: 100%; max-width: 540px; padding: 0;">
<div style="vertical-align: top; color: #b8b8b8; font-family: arial; font-size: 10px; margin-bottom: 3px; width: 100%; max-width: 540px;"><span style="color: #999999;">Lending &amp; Refinance</span></div>
<div style="display: block; color: #2e8cf0; font-size: 13px; text-decoration: none; font-family: arial; margin-bottom: 3px; width: 100%; max-width: 540px;"><a style="color: #2e8cf0; font-size: 13px; text-decoration: none; font-family: arial;" href="https://www.washingtonpost.com/news/where-we-live/wp/2016/09/22/mortgage-rates-wander-lower-this-week-and-could-be-headed-down-even-more/" target="_blank">Mortgage rates wander lower this week and could be headed down even more</a></div>
<div style="display: block; font-family: arial; font-size: 13px; color: #808080; width: 100%; max-width: 540px;">&ldquo;The 10-year Treasury yield declined after last week&rsquo;s post-Brexit high in an...</div>
</td>
</tr>
</tbody>
</table>
</td>
</tr>
<tr>
<td style="width: 100%; border-top: 1px solid #e5e6e9; border-bottom: 1px solid #e5e6e9; padding: 10px;">
<table style="margin: 0px auto; border-collapse: collapse; width: 100%; border: none;">
<tbody>
<tr>
<td style="width: 50px; padding: 0 10px 0 0; vertical-align: top;" valign="top" height="50">
<div style="vertical-align: top; height: 50px; max-height: 50px; width: 100%;"><img style="width: 50px; height: 50px; vertical-align: top;" src="http://www.mortgagespeak.com/sites/default/files/track_news.png" alt="" width="50" height="50" /></div>
</td>
<td style="line-height: normal; vertical-align: top; text-align: left; width: 100%; max-width: 540px; padding: 0;">
<div style="vertical-align: top; color: #b8b8b8; font-family: arial; font-size: 10px; margin-bottom: 3px; width: 100%; max-width: 540px;"><span style="color: #999999;">Lending &amp; Refinance</span></div>
<div style="display: block; color: #2e8cf0; font-size: 13px; text-decoration: none; font-family: arial; margin-bottom: 3px; width: 100%; max-width: 540px;"><a style="color: #2e8cf0; font-size: 13px; text-decoration: none; font-family: arial;" href="http://finance.yahoo.com/news/sales-existing-u-homes-unexpectedly-140005742.html" target="_blank">Sales of Existing U.S. Homes Unexpectedly Declined in August</a></div>
<div style="display: block; font-family: arial; font-size: 13px; color: #808080; width: 100%; max-width: 540px;">A shortage of available properties for sale continues to hinder the market, t...</div>
</td>
</tr>
</tbody>
</table>
</td>
</tr>
<tr>
<td style="width: 100%; border-top: 1px solid #e5e6e9; border-bottom: 1px solid #e5e6e9; padding: 10px;">
<table style="margin: 0px auto; border-collapse: collapse; width: 100%; border: none;">
<tbody>
<tr>
<td style="width: 50px; padding: 0 10px 0 0; vertical-align: top;" valign="top" height="50">
<div style="vertical-align: top; height: 50px; max-height: 50px; width: 100%;"><img style="width: 50px; height: 50px; vertical-align: top;" src="http://www.mortgagespeak.com/sites/default/files/pr.png" alt="" width="50" height="50" /></div>
</td>
<td style="line-height: normal; vertical-align: top; text-align: left; width: 100%; max-width: 540px; padding: 0;">
<div style="vertical-align: top; color: #b8b8b8; font-family: arial; font-size: 10px; margin-bottom: 3px; width: 100%; max-width: 540px;"><span style="color: #999999;">Press Release</span></div>
<div style="display: block; color: #2e8cf0; font-size: 13px; text-decoration: none; font-family: arial; margin-bottom: 3px; width: 100%; max-width: 540px;"><a style="color: #2e8cf0; font-size: 13px; text-decoration: none; font-family: arial;" href="http://finance.yahoo.com/news/u-bank-launches-inaugural-u-122000165.html" target="_blank">U.S. Bank Launches Inaugural U.S. Bank Possibility Index, Measuring Americans...</a></div>
<div style="display: block; font-family: arial; font-size: 13px; color: #808080; width: 100%; max-width: 540px;">&ldquo;Americans spend the majority of their time in three main areas of life &ndash; wor...</div>
</td>
</tr>
</tbody>
</table>
</td>
</tr>
</tbody>
</table>
</td>
</tr>
</tbody>
</table>
</td>
</tr>
<tr>
<td>&nbsp;</td>
</tr>
<tr>
<td style="padding: 0 0 20px 0;" align="center">
<p><span style="color: #2e8cf0;"><span style="font-family: arial, helvetica, sans-serif; font-size: x-small;">Contact Us</span></span></p>
<p><span style="font-family: arial, helvetica, sans-serif; font-size: x-small; color: #999999;">1625 W. Balmoral Avenue</span></p>
<p><span style="font-family: arial, helvetica, sans-serif; font-size: x-small; color: #999999;">Suite #2</span></p>
<p><span style="font-family: arial, helvetica, sans-serif; font-size: x-small; color: #999999;">Chicago, IL &nbsp;60640</span></p>
</td>
</tr>
</tbody>
</table>
</td>
</tr>
</tbody>
</table>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>

**Comment by saurabhd** [comment]
The "updated newsletter image" shows only the bottom half of the newsletter b/c I wanted to show you how the "LinkedIN Recommended" check-mark image and "Share" text links should look. The rest of the newsletter should follow the code I am emailing to you separately as well.

![linkedin-recommendations-web-page-new](https://cloud.githubusercontent.com/assets/2010385/19228492/6d3a8f3c-8ee3-11e6-9c9b-1432cc6049c3.png)
![linkedin-recommended-newsletter-new](https://cloud.githubusercontent.com/assets/2010385/19228493/6d463e7c-8ee3-11e6-9a14-54f9ed703758.png)
[mortagage email content.txt](https://github.com/snehal-addweb/Mortgagespeak/files/518905/mortagage.email.content.txt)

**Comment by gatsby8870** [comment]
Hello, I updated the newsletter code so kindly used the attached.

No big changes, just cosmetic changes.

Thank you!

[Newslettercode10-12-16 (1).txt](https://github.com/snehal-addweb/Mortgagespeak/files/525803/Newslettercode10-12-16.1.txt)

**Comment by gatsby8870** [comment]
In the new web page, I would like the background color of the headline counter (shown in image with numbers "975" to go from that "gray" to the same light blue color used in the dropdown filter directly beneath it (showing "All Topics").

The light blue is a little nicer. Thanks!

**Comment by Krina-Addweb** [comment]
Hello Greg,

Above Mentioned changes are done over mortgagespeak.com. 

Further, if you face any issues with image for "LinkedIN Recommended" as it was blurred, please provide us a good quality image for the same.

Thanks

**Comment by gatsby8870** [comment]
The newsletter is coming along great and here are edits:

**--NEWSLETTER--**

**1. Top Blue Header**
- Change text "Newsletter" to "News Intelligence"
- Change text in lower row from "Multiple news sources. One newsletter." to "The news that matters most."

**2. Headline Summary (numeric area)**
- Bold text "LinkedIN Recommendations" and change the color of the ending "IN" to #0077b5
- Change the text "Company Headlines" to "Tracked Companies", and the text "Sector Headlines" to "Tracked Sectors"

**3. Login Green Area**
- Change the hyperlinked text "Your custom "My Page:" to "Your custom news page:"

**4. LinkedIN Blue Area Counter**
- Separating the above green area and the lower "LinkedIN" blue box, there are two rows (one with an orange line in it). Remove the second row containing the orange row and keep the first.
- In the lower LinkedIN box , change the font-family for "Grow your brand. Look like a genius." from "Tahoma" to "Arial"

**5. Headline Table Area (lower)**
- Increase the character count in gray text underneath the hyperlinked headline by ~ 60 characters. The gray text is going into two rows now (good) but let's extend it further but not 3 rows.
- Replace the existing "LinkedIN Recommended" image with image emailed to Saurabh..
- Add two rows below the Linked Recommendations image row: See image emailed to Saurabh.
  - First new row is blank.
  - Move the share text links into the second of two new added rows (bottom).
  - Make the original row with the LinkedIN Recommend image one cell (currently 2);
  - When the "LinkedIN Recommended" image is not assigned, its row should be removed. If not, there is too much spacing before the share text links.
- Remove the text "Share on:" keeping only the text links
- The LinkedIN and Twitter "Share" text links along the right are not functioning properly. Twitter link is not providing the title and the LinkedIN is showing some html code; Add LinkedIN solution to checkmark image as well.
- Add 2 additional spaces between share text links
- Change the share text "Google+" to just "G+"

**6. Bottom of newsletter**
- At the bottom, change the uppercase "U in "Contact Us to lower case"u"; "Contact us!" (add exclamation point)

**--WEB PAGE EDITS--**
- Move page title over a little bit to align "L" in "LinkedIN" with left border of above "My Page" tab; The page title just looks a little too far to the left.
- Unbold text color for the text "Articles Recommended" in the light blue counter box but keep the numbers bold
- Change text in gray row from:
  - "Share curated news and grow your company!" to "Curated headlines ideal for sharing on LinkedIN!"
  - "Search By Topic:" to "Sort By Topic:"

**Comment by saurabhd** [comment]
Please make sure they see use these images in their "original size" and not "best fit" or smaller. Text can become blurry.

---
1. --Use new "LinkedIN Recommended" image--

(attached)
1. --Add 2 news rows to newsletter headline area-- 

From GitHub, I thought the programmers may enjoy an image of how it should look.

The reason why I am adding 2 new rows is b/c when viewing the newsletter in a cell phone, the "LinkedIN Reccommended" image and the share links are too long for the single row they are upon (too wide). So I had to separate the image and the text links with new rows. 

When there is no assigned "LinkedIN Recommended" image, the image row should be removed. If not, there is too much space between all the rows.

![linkedin-recommended-image](https://cloud.githubusercontent.com/assets/2010385/19426572/4dbb8ea4-945b-11e6-8427-d569305086d3.png)

![unnamed](https://cloud.githubusercontent.com/assets/2010385/19426576/5164e19a-945b-11e6-8f21-262cc6a754ce.png)

**Comment by Krina-Addweb** [comment]
Hello Greg,

Above mentioned edits are done.

Thanks.

**Comment by gatsby8870** [comment]
Hello, here is feedback with specific mention to the share text links not working properly.

**Newsletter**:
- Top Blue Header: Reduce cell padding from current "40px" to "20 px"; this moves the logo and text rows over to the left
- Share text links not working properly:
  - LinkedIN Share text link.recommended image is pulling the text of my web page's disclaimer for the gray teaser/summary text
  - Twitter: missing title and gray teaser/summary text
- Reduce space between share text links from 4 spaces to 3; this helps it fit on one line

**Web page:**
- Move the page's title (large LinkedIN Recommendations image and text) over to the right a couple of space; it's over a tiny bit too far to the left

Thank you.

**Comment by Krina-Addweb** [comment]
Hello Greg,

Above mentioned changes were done.

Thanks

**Comment by gatsby8870** [comment]
Hello, the newsletter share links are not working fully:

LinkedIN: missing the gray summary/teaser text. Now it is just repeating the title already there.
Google +: missing the title and the gray summary/teaser text

Thank you.
