### ISSUE TITLE
"Connected Companies"

### ISSUE THREAD

**Issue by gatsby8870** [snehal-addweb/Mortgagespeak#69]
**Estimate**: "Connected Companies" page

Overview: Create a search page where I can select a company and see which companies a "connected to it".

The page offers two drop-down filters each using the "company tags" taxonomy and searches only "Press Releases" content. 

The drop-downs are titled:
1. "Source Company"
2. "Connected Company"

In the first drop-down, I would select the "source company" and in the "Secondary Company" drop-down I would select either:
1. "All Companies" (default selection) or
2. (any of "company tag")

The results show in the table format we have now: Date, Headline, Gray Text, Mortgage Topic:, Company:, etc.

What is the time needed for this?

**Comment by saurabhd** [comment]
Create a search page where I can select a company and see which companies a "connected to it".

> > Can you please elaborate. How are these companies inter related?

**Comment by gatsby8870** [comment]
They are connected by both being tagged (company tag) within the same "Press Release" headline.

**Comment by saurabhd** [comment]
Okay, need to check its feasibility. 

Would let you know estimates tomorrow.

**Comment by gatsby8870** [comment]
My goal is to see which companies are connected to one another. I would select "Company X" and it would show me every headline (press release) that contains both "Company X" and any other company tag term.

I could do the above to see all other companies connected to it or specify a company tag to see which headlines contain that company tag and "Company X".

**Comment by roshni-addweb** [comment]
Estimates would be 8 working hours.

**Comment by gatsby8870** [comment]
Correct.

I am looking to present my client a list of companies their competitors are connected to. "Here is your "competitor" (Source Company) and here are all the companies who are connected to this competitor via Press Releases.

The results can show all the companies (as mentioned above) or they can look for all the headlines that mention the competitor (source company) and a specific company.

**Comment by Krina-Addweb** [comment]
Hello,
These changes were made. Here is the [link](http://mortgagespeak.com/connected-companies) 

Please let me know your thought for the same. 
Thanks

**Comment by gatsby8870** [comment]
Thank you. I will review today.

Could you:
1. Add a numeric counter, perhaps something similar to the one here: http://www.mortgagespeak.com/linkedin-recommendations
2. Remove the line gray line underneath the page title.

**Comment by Krina-Addweb** [comment]
Hello Greg,

Above Edits were Done.

Thanks
