### ISSUE TITLE
Edits

### ISSUE THREAD

**Issue by gatsby8870** [snehal-addweb/Mortgagespeak#70]
Hello!

Kindly perform these edits:

Web Site: 
1. On content-level pages (see below 2 examples), change the font style to Arial, font color to #333333 and line height to 2.25:
[press releases](http://www.mortgagespeak.com/millennial-first-time-homebuyer-demand-does-not-increase-defect-fraud-and-misrepresentation-risk)
[perspectives](http://www.mortgagespeak.com/how-advance-your-legal-research-using-real-property-information)
2. Remove top gray row (located above page title) and remove the thin left, top and right borders gray borders.
3. Edit "Excerpt" sticky pop up:
Remove the white text "(What's this?)"
Change text in "View on web" button to "Read full article"
4. The top banner ad hyperlink doesn't work unless the user is logged out. Should work to all users logged in or not.
See top page ad [here](http://www.mortgagespeak.com/global-dms) or [here](http://www.mortgagespeak.com/first-american-mortgage-solutions) as 2 examples
5. The site's social networking icon share codes don't share the gray summary text in the shared post (the newsletter now does with your recent changes). Update site share codes to share gray summary text like newsletter does. Icons located here:
[News](http://www.mortgagespeak.com/news)
[Press Releases](http://www.mortgagespeak.com/press-releases)
[Perspectives](http://www.mortgagespeak.com/perspectives)
[LinkedIN Recommendations page](http://www.mortgagespeak.com/linkedin-recommendations)
Sticky Pop Up
Content level pages:
Example 1: [Press Release](http://www.mortgagespeak.com/millennial-first-time-homebuyer-demand-does-not-increase-defect-fraud-and-misrepresentation-risk)
Example 2: [Perspectives](http://www.mortgagespeak.com/how-advance-your-legal-research-using-real-property-information)
6. Update quotes file (shown on home page) with quotes emailed to Saurabh. Some quotes had typos.
7. In the newsletter, increase the font size of the hyperlinked headlines only to 20px and the gray summary text only to 14px. Everything else stays the same.
Remove share code used in hyperlinked image "LinkedIN Recommended" and add image description & title text: "Share this on LinkedIN."
Increase "Unsubscribe" text size at bottom of newsletter to 12p, if possible
Capitalize the "r" in "recommendations" located in the blue LinkediN recommendations box; To look like. "58 LinkedIN Recommendations", for example.

**Comment by Krina-Addweb** [comment]
Hello Greg,

Above changes are completed.

For the changes regarding newsletter: We have removed link from hyperlinked image "LinkedIN Recommended" & added image description & title text: "Share this on LinkedIN."

Increase "Unsubscribe" text size at bottom of newsletter to 12p, if possible

> > This is not possible.

Please let me know if you want some further changes.

Thanks!

**Comment by gatsby8870** [comment]
Everything looks great.

Kindly add these edits:
1. Have Editor's Pick URL open in the "Excerpt" tab/sticky pop up instead of new browser window. Should function like all other content.
2. Newsletter: For the hyperlinked headline and gray summary text only, change the line-height 1.5px

**Comment by Krina-Addweb** [comment]
Hello Greg,

Above Mentioned edits were done.

Thanks.

**Comment by gatsby8870** [comment]
Great!

Last request for this issue, would you increase the character of the text shown in the newsletter (shown underneath the hyperlinked headline)? There is empty space there but I do not want it to break into 3 lines so I think 40 additional characters would work.

Thank you!

**Comment by Krina-Addweb** [comment]
Hello Greg,

Above mentioned edits were done.

Thanks.
