### ISSUE TITLE
Statistics page

### ISSUE THREAD

**Issue by gatsby8870** [snehal-addweb/Mortgagespeak#71]
Hello.

The site's statistics page (http://www.mortgagespeak.com/my-page/stats) is not recording all user clicks to the newsletter category: "Mortgage Solutions "News Intelligence" - Staff.

For example, this "[Newsletter Clicks](http://www.mortgagespeak.com/node/3742/simplenews_statistics/clicks)" shows this user's click: 

- http://www.mortgagespeak.com/american-financing-celebrates-thanksgiving-helping-families-free-refinancing-remodeling-and-monthly
- Mwheaton@firstam.com
- Wed, 11/16/2016 - 14:12

Yet for 11/16/16, this user's name and click is not shown. Log in using:
- un: Greg123
- pw: Greg789

I believe the error is related my changing the original newsletter's category name from "FAF" (?) to "Staff" and I created a new "Admin" version. I did this b/c this (FAF) client adds lots of new staff and creating new user accounts and assigning companies and news topics for each user was very time consuming.

So I renamed the original newsletter, created another newsletter for key users, and placed all users within those two categories (they all get one of two usernames and pws).

I seem to recall being told not to change the category name. :(

**Note**:

I don't know if my two newsletter solution is valid for the long-term so please don't erase the ability to issue unique newsletters per user as I may need to revert back at some point.

Please let me know if fixing this will require a lot of time. I will revert.

Thank you!

**Comment by roshni-addweb** [comment]
Hello Greg,

Above changes were made for below mention 3 Newsletter categories, but if you will change name of any category then the FAF password will not be replaced for that category. Please let me know if you want any further changes.
"Mortgage Solutions "News Intelligence" - Staff
Mortgage Solutions "News Intelligence" - Admin
Mortgage Solutions "News Intelligence"

Note : If you revert your category to unique category as before i.e Mortgage Solutions "News Intelligence" it will work as it was working before.
