### ISSUE TITLE
Mobile App Quote

### ISSUE THREAD

**Issue by gatsby8870** [snehal-addweb/Mortgagespeak#72]
Can you provide a general quote for building a mobile app? My focus is to provide a news feed mobile app delivering 

1. Content feeds from my site's pages:

- LinkedIN Recommendations
- News
- Press Releases

2. Display an advertisement (300 x 250) ad every 5th headline: 

- Drupal ad (my site)
- Google AdSense ad

3. Enable user article sharing and commenting on LinkedIN and other social networks.

**Comment by roshni-addweb** [comment]
Hello Greg,

Here's some Queries:

1) Do we need to create designs or mockups would be provided by you?
2) Login and Registration is also required in the application?
3) Could you please elaborate more on "commenting on LinkedIN and other social networks." part?
4) Do you have any preference for application logo and splash screen for application?

Please confirm my below Assumptions:

1) Drupal ad & Google AdSense and the size of content ( image size 300 x 250 ) will be handled by you only. I mean any changes in taxonomy or anywhere else will be handled by you only from drupal site admin panel. Please confirm.
2) This application will be built in ionic framework and this application will be built for ANDROID and IOS for all type of devices support ( MOBILE / TABLETS ).- Please confirm.
3) Article sharing will only be available to you for LinkedIN, facebook, twitter, Googleplus and email, as only these are the available social sites on your website.
4) Ads should be same as website i.e PR ads are displayed on Press Releases and Perspectives pages only and random ads (google and drupal ads) are displayed on other pages. - Please confirm

Thanks

**Comment by gatsby8870** [comment]
Hello and thank you for your questions. Here is an added item and my replies:

**Added Request**
Please add a dropdown filter for the "News" and "LinkedIN Recommendations" mobile pages to reach their dropdown pages(e.g. Fraud, AMC, etc). Just like the filter already here: http://www.mortgagespeak.com/news and here: http://www.mortgagespeak.com/linkedin-recommendations

**Query replies:**

1. No, you do not need to create designs. I will provide mockups.
2. Yes, registration/login would be required:
-- email address (one form field only, not two)
-- password (show text while typed)
-- checkbox (yes/no): "Get our newsletter"
3. This is simple social network sharing. The networks provide commenting on a shared post. 
4. Yes, I would like an application logo but not splash screen.


**Assumption replies:**

1. Correct.
2. Correct.
3. Correct
4. **Unclear** I envision creating and assigning ads for the mobile device's pages the same way I do now for the site. At my site, a new Drupal ad called "Client XYZ Mobile ad" would be created. I would assign this ad to a to a specific page. This would show that new ad within the assigned page in the mobile app. I welcome your thoughts/suggestions.

Thank you.

**Comment by roshni-addweb** [comment]
Hello Greg,

Thanks for your reply.

According to provided scope of work, we would require 10-11 weeks of development.

Further, one more assumption:

-- checkbox (yes/no): "Get our newsletter”
> Where you want us to add this field ? ( Login  / Registration ) as currently this is no where in website.

Please confirm.

**Comment by gatsby8870** [comment]
Hi, yes that location is just fine.

Sorry for the delay!

**Comment by roshni-addweb** [comment]
Hello Greg,

Ok I will add this field in Registration form. Further Please confirm estimation provided to you.

Thanks

**Comment by gatsby8870** [comment]
Hello, here are project edits I wanted to share:

**Removed items:**

1. Login and registration functionality (~ 65 hours).
2. Google+ and email article sharing (keep only LinkedIN and Twitter).

**Added items:**

1. Article sharing "Copy URL" functionality

**Attachments**
Here are 3 image designs.

**Question:**
Will the app give a notice to the user of new articles that day or a notification in the phone's top bar? What are the options and cost (general) here?

![main-page-with-frozen-footer](https://cloud.githubusercontent.com/assets/18587752/21213113/f99d9c92-c257-11e6-9d4b-583de3694118.png)
![press-release-page-with-rga-ad](https://cloud.githubusercontent.com/assets/18587752/21213112/f99d6ce0-c257-11e6-9eaf-0e5b8df75aaf.png)
![source-content-page-with-frozen-social-network-footer](https://cloud.githubusercontent.com/assets/18587752/21213111/f99d5d68-c257-11e6-8fbf-dc0e33a2b7b9.png)

**Comment by roshni-addweb** [comment]
Hello Greg,

Thanks for your response.

We will going to remove the Login and Registration screens from our scope of work and will add the "Copy URL" feature.

We have also reviewed the mock-ups you have provided and based on those we also have some questions and assumptions listed below.

1) Only News screen is having filters at the top right side of the screen and based on that we assume to have the related filters in each of the screen ( Linkedin, News and Press release ) at the same position. - Please confirm.

2) In the website all the three listing pages have social sharing buttons but in mock-ups there are no such buttons on listing, so we will not add those button on listing pages and add LinkedIn, Twitter and Copy URL buttons on detail pages only. - Please confirm

3) In the Press Release (Provided mock-ups) there is 2nd item in GRAY color having title "12 Problems Good PR Can Solve", so why that block is in different color? Please provide some explanation of the differentiation in color.

4) These mock-ups are good for understanding but at later stage ( Development ), we will need actual PSDs of these mock-ups of all the screens listed in the estimation. Because based on those only we will create our HTML.

Regarding Revised Estimation from total given hours only Login and Registration screen's hours are deducted rest of the hours will remain same as they are.

Thanks

**Comment by roshni-addweb** [comment]
Hello Greg,

Please let me know your input about the points mentioned in above comment.

Thanks

**Comment by gatsby8870** [comment]
Hello, here is my feedback and thank you for your patience:

1. The filter should be on the News page, the pages presented within its [dropdown] (http://www.mortgagespeak.com/admin/structure/taxonomy/news_topics) and LinkedIN Recommendations. The Press Release page does not need it.

2. Correct, the only buttons needed to show are "LinkedIN, Twitter and Copy URL".

3. You can disregard. This was an illustration for my client but it not accurate with the dimensions shown. It is an example of how an advertisement will generally look.

4. I will provide PSD files of anything you need.


Questions:

1. Is the function to notify app users of new content or a special article? I believe there are two types of notice but I am not sure. Could you tell me the hours needed for something like this?

Thank you.

**Comment by roshni-addweb** [comment]
Hello Greg,

Here are few questions:

1) We will create a new campaign for mobile app ads. So that you can create ads for mobile only and that ads will be displayed after every 5th headline. Is it okay for you? - Please confirm
2) We need to display ads after every 5th headline only and not on top, sidebar, etc. - Please confirm
3) Do we need to display ads in detail page?

Thanks

**Comment by gatsby8870** [comment]
Hi, here are my replies:

1. Yes.
2. Yes.
3. No.

Thank you.

**Comment by roshni-addweb** [comment]
Hello Greg,

Thanks for your response.

Here are few more concerns from my end regarding application.

1) Could you please provide me the actual mock-ups so that we can start preparing the HTML based on those mock-ups?
2) I have tried using the existing google ads code from website in side the application and as expected it is not working in application and we are using ionic for building an application so according to ionic, you need to create account in admobs (https://apps.admob.com) using for getting ads for mobile app. Please let me know if you face any issue.

Thanks

**Comment by gatsby8870** [comment]
Hello!

1. Sure, I will attached those PSD images tonight.

2. I created an AdMob account. The email address to use for login is: greg@mortgagespeak.com and the pw is: GregKnicks88708. If helpful, here is additional information:

greg@mortgagespeak.com
Publisher ID: pub-9613794206213062

The ad unit size I want to use is 300x250.

Please let me know what else you may need.
Thank you!

**Comment by roshni-addweb** [comment]
Hello Greg,

Thanks for the information.

I will check this out and will let you know if any further assistance needed.

Thanks

**Comment by gatsby8870** [comment]
GitHub would not allow me to attach PSD files so I am emailing them to Saurabh.

Let me know if you need anything else.

Thank you!

**Comment by gatsby8870** [comment]
Please add "push notifications" as discussed with Saurabh. 

Thank you!

**Comment by roshni-addweb** [comment]
Hello Greg,

Could you please provide me your apple developer account details, so that I can create the provisioning profile and certificate for the application.

Thanks

**Comment by gatsby8870** [comment]
My developer credentials have expired so I need to renew them.

I will let you know when that is done. Here are my access credentials, however:

Apple ID: gatsby8870@msn.com
Password: Knicks8870Sherlock

**Comment by gatsby8870** [comment]
Hello, my Apple Developer membership has been renewed.

You should be able to do what you need to now. If you need additional info, here is some helpful info:

Apple ID: gatsby8870@msn.com
Password: Knicks8870Sherlock

Team Name: Greg JANECKA
Team ID: SMH8TQCVD4
Activation Date: Jan 11, 2017
Expiration Date: Jan 11, 2018

Thank you!

**Comment by roshni-addweb** [comment]
Hello Greg,

I am not able to login with AdMob account.It seems like password has been changed so, could please provide me new password.

Thanks

**Comment by gatsby8870** [comment]
Hello, sorry for the issue. Please try pw: Knicks887088701234

Let me know if it does not work. Thank you for your hard work!

**Comment by roshni-addweb** [comment]
Hello Greg,

Thank you for your response and password is working now. Could you please provide me psd for application icon.

**Comment by gatsby8870** [comment]
It is looking **exceptional!** Congratulations to you and the programmer(s)!

Here are edits:

**Bottom 3 links (Recommended for LinkedIN, News Headlines, Press Releases):**

1. Reduce text font size to be like bottom 3 links in attached image (see left arrow in Lower Text Links.png)
2. Make the vertical line between these 3 section links equally spaced.
3. Edit text "News "Headelines" to "News Headlines" (no second "e" in "Headlines")
4. When a bottom link section is loaded, make its bottom link text color #126EDC. Since "Recommended for LinkedIN" is default, it should be #126EDC initially
5. On click, add background color around the link area to similar to (see middle green arrow in Lower Text Links.png)

**Top right filter: "All Topics":**

1. Rename to "Topics"
2. Invert color scheme. Make the background the orange color and the text white.
3. Not all news topics are being shown (now stops at "Government")


**Top blue header text (shown after a bottom link click)**

1. When "News Headlines" bottom link is clicked, the text in top blue header is missing ending "s" in "Headlines"
2. Make "back" arrow larger and move text left closer to arrow (about 10 pixels away?)


**Advertising**

1. The ads shown now are likely placeholders but true dimensions are 300w X 250h
2. The ads should display on all 3 tabs. In Drupal, I can assign ads to sections (Recommended for LinkedIN, News Headlines, and Press Releases)


**Misc**

1. Change status message while articles load from "Loading initial articles" to "Loading ..."
2. No search bar needed on News and Press Releases pages
3. On press release section, the tabs should not show the "Company tags". Show date only


**Detail page (content shown post-tab click)**

1. The bottom 3 section links (Recommended..., News Headlines, Press Releases) should not display (only share and copy URL buttons)
2. Content hosted by me should load fully in-app
3. Content hosted elsewhere should load landing page (see Content NOT hosted by MortgageSpeak.png). Load the content from "Pop up Text" field.in browser and "More" button links to source content URL.
4. Increase title font size
5. Increase line spacing
6. Increase left and right margin by 5 px each


**Tabs on all pages:**

1. Increase line spacing for headline
2. Increase margin between date text and lower "Mortgage Topic" text; (they are too close to one another.)
3. Change "Mortgage Topic" to "Topic"
4. On all tabs, change lower date format to: mm--dd--yy (from yy-dd-mm)
5. Some article tabs shows "&nbsp;" in headline and gray text. How can this be resolved? Non-ascii?
6. Darken gray text on tabs

Note: Future requested PSD file to come.

Thank you for your hard work!

![lower-text-links](https://cloud.githubusercontent.com/assets/18587752/22139074/9be03830-dea9-11e6-9ea2-c8d04bbba0a9.png)


![content-not-hosted-by-mortgagespeak](https://cloud.githubusercontent.com/assets/18587752/22138910/a635ce86-dea8-11e6-8f58-71c5f333c17d.png)

**Comment by roshni-addweb** [comment]
Hello Greg,

Here are the update for your edits.
1. Bottom 3 links (Recommended for LinkedIN, News Headlines, Press Releases):
=> Done.

2. Top right filter: "All Topics":
=> Done.

3. Top blue header text (shown after a bottom link click)
=> Done.

4. Advertising
=> First section is done. For point #2, I have developed the screens like, whenever any advertisement is there for any of the listing page from website then only it will be displayed. So If you will assign any ads for Linkedin Articles you will be able to see same in the Mobile.

5. Misc
=> Done.

6. Detail page (content shown post-tab click)
=> All tasks are done except point #3, for that I need to discuss on skype.

7. Tabs on all pages:
=> Done.

Thanks

**Comment by gatsby8870** [comment]
Hello, this is likely to change but here is a application logo you can use.

Thank you!

![idea-for-application-icon](https://cloud.githubusercontent.com/assets/18587752/22291418/ec807d10-e2cb-11e6-98a8-0b10b8893f26.png)

**Comment by gatsby8870** [comment]
Here is the updated mobile ad in the suggested dimensions.

Thank you!

![sample-2-mobile-ad](https://cloud.githubusercontent.com/assets/18587752/22291847/02ece3f2-e2ce-11e6-8f95-45c083921e92.png)

**Comment by gatsby8870** [comment]
1. Move "Loading..." text down on the loading display message.

2.  On the LinkedIN Recommendations page, increase height of "Topics" drop-down and move text left more to take advantage of that room so that collectively we can fit the topic titles that break into two lengthly lines.

3.  The bottom 3 links (Recommendations for LinkedIN, News, Press Releases), the entire box area (when text and icon is selected and turns blue), is raised 1 pixel too high. It is 1 pixel higher than the other two non-selected boxes and the bottom of the selected area is "raised" up 1 pixel showing a 1 pixel lighter area.

4. Make the bottom button area that says "Press Releases", make that text two lines so it's similar to the other two boxes text lines

5.  The bottom 3 buttons area ("Recommended for LinkedIN, News, Press Releases) is missing its darker top border line which is shown on the "content-level" pages above the 3 buttons: LinkedIN, Twitter, Copy URL.

6. Change the ad display to be shown as the 2nd tab on the initial page display and display after every 4th tab instead of after every 5th tab.

7. When the orange topics dropdown is used and the page loads, that loaded page should start at the top of the page. Now it's the second tab or lower.

8. On the content level pages (pages with LinkedIN, Twitter and Copy URL buttons), move the "More" button to be left-aligned, not center-aligned.

9. The content tabs for the "News Headlines" page, the tag for "Company" is shown and should not be; remove it.

10. The content tabs show a tag "Topic :" and this semi-colon should be moved left once so it comes directly after the "c" in "Topic".

11. On content-level pages (showing the LinkiedIN, Twitter and Copy URL buttons, the blue header left-pointing arrow should be like before (thinner; not boldered) and left-aligned so it is the same as the lower left-aligned content. Also please move "down" the headline.

12. Please edit the white text in the top blue header for the "Recommendations for LinkedIN" button currently showing as "LinkedIN Articles" to "Rec. for LinkedIN".

Thank you for all your hard work!!!



![loading-message-moved-down](https://cloud.githubusercontent.com/assets/18587752/22451208/18939a1c-e732-11e6-908a-fe716db4de7d.png)

![bottom-area-when-selected-is-raised-1-pixel-too-high](https://cloud.githubusercontent.com/assets/18587752/22451367/8f5a5e32-e733-11e6-93cb-7a22c3240819.png)

![add-border-to-linked---news---press-releases-and-break-into-two-lines](https://cloud.githubusercontent.com/assets/18587752/22451648/e420f96a-e735-11e6-9eba-77b1083adb3b.png)

**Comment by gatsby8870** [comment]
Hello, here is some app feedback:

**Advertisement:**
Edit advertisements to display as the 2nd tab on all pages and then as the 5th tab thereafter (aka after the 4th content tab)

**Tabs:**
Change "date" format from numeric-only (e.g. "02-17-2017") to alpha-numeric and use only 3 letters (e.g. "Feb 4"). No "year" is necessary.
Swap the placements of the "date" and "Topic" tags. Then remove the "Topic" tag. This places the date lower in the tab with room between it and the gray text.

**External content:**
When external content is loaded. there is a new gray top header. This header has back and forward arrows and a URL field that does not offer any functionality. Edit the top header to be like in this image ("External header...png") offering only a back arrow and some of the headline text
Increase width of orange topics bar and continue to use "..." when topic name is too long
When using the "Copy URL" button, edit the message to include" an exclamation point after the word Success (Success!) and edit the "Copied" text to "URL copied to clipboard."

**Recommended for LinkedIN:**
Increase width orange dropdown like in image ("Wider orange topics dropdown.png") and keep topics text on one row. Use "..." when topic text is too long (no line break; this replaces earlier request.)

**Bottom Button Row** (Recommended for LinkedIN, News Headlines, Press Releases):
The act of clicking a button temporarily raises the gray button image and text and then lowers it on load. Please make sure it stays in same (no movement)

Thank you for your hard work!


![external-content-top-header](https://cloud.githubusercontent.com/assets/18587752/22631133/172b8e2a-ebcc-11e6-98f8-ca39a37e329d.png)

![wider-orange-topics-dropdown](https://cloud.githubusercontent.com/assets/18587752/22631176/b74a47c0-ebcc-11e6-87c5-5fbaa4f37cff.png)

**Comment by hardik-addweb** [comment]
Hi @gatsby8870 ,

Please review our comment inline.

Advertisement:
Edit advertisements to display as the 2nd tab on all pages and then as the 5th tab thereafter (aka after the 4th content tab)

> We will do this as per our discussion on skype. Advertisement will be displayed on 2nd position after first article in all three tabs (Linkedin, News and Press Release). And then it will display after every 4 articles.
This change will take **1 Hour** 

Tabs:
Change "date" format from numeric-only (e.g. "02-17-2017") to alpha-numeric and use only 3 letters (e.g. "Feb 4"). No "year" is necessary.
Swap the placements of the "date" and "Topic" tags. Then remove the "Topic" tag. This places the date lower in the tab with room between it and the gray text.

> We will do it. Design changes are also needed in this.
This change will take **30 Mins**

External content:
When external content is loaded. there is a new gray top header. This header has back and forward arrows and a URL field that does not offer any functionality. Edit the top header to be like in this image ("External header...png") offering only a back arrow

> For this we have removed the top bar from the external link browser. User will click back button from his device to get back to the Application.
This change will take **30 Mins**

 and some of the headline text
Increase width of orange topics bar and continue to use "..." when topic name is too long

> For this, adding (...) dots in select box is not allowed in simple select option dropdown. So we need to change the structure of the dropdown box and need to add some custom structure in this. So the time for this change will take **4 Hours**. As design changes will be there along with custom coding for getting custom dropdown box. 

When using the "Copy URL" button, edit the message to include" an exclamation point after the word Success (Success!) and edit the "Copied" text to "URL copied to clipboard."

> We will do it.


Recommended for LinkedIN:
Increase width orange dropdown like in image ("Wider orange topics dropdown.png") and keep topics text on one row. Use "..." when topic text is too long (no line break; this replaces earlier request.)

> As mentioned above this change will take 4 Hours.

Bottom Button Row (Recommended for LinkedIN, News Headlines, Press Releases):
The act of clicking a button temporarily raises the gray button image and text and then lowers it on load. Please make sure it stays in same (no movement)

> This is bug from our side so no extra hours needed for this. We will resolve it and will not charge extra for this.


Please confirm all the points and let us know if any issue.

**Comment by gatsby8870** [comment]
All items are approved except for:

**1. "External content:**
"When external content is loaded. there is a new gray top header. This header has back and forward arrows and a URL field that does not offer any functionality. Edit the top header to be like in this image ("External header...png") offering only a back arrow

For this we have removed the top bar from the external link browser. User will click back button from his device to get back to the Application.
This change will take 30 Mins"

Questions:
1. Is there no other plugin we can use? I think a plugin is important b/c. the user still feels they are connected to the app vs a web browser. I use other apps that show the plugin I would like to have, if it is helpful to refer to you.
2. Additionally, there is no "back" button in Apple phones and I don't want users to have to find this app again just to do back.


**2. "Increase width of orange topics bar and continue to use "..." when topic name is too long"**

My issue with the estimate is the text used for the topic names (e.g. "Document Services") naturally uses a "..." when it is longer than the drop-down width.

I simply want to increase the width of this drop-down and let the "..." happen. No line break but that is not happening now anyway.

Thank you.

**Comment by hardik-addweb** [comment]
Hi @gatsby8870,

**1. "External content:** 

> We are still working for finding the other solution / plugin for opening external links.

**2. "Increase width of orange topics bar and continue to use "..." when topic name is too long"**

>We have resolved this issue without any external library. We have found a solution using jQuery only. Dots (...) were not displaying in devices even after we have increased the width of the dropdown. So we have to do some R&D for this and finally got the solution using jQuery and all these efforts took **4 hours** for us to get the solution.

**Comment by gatsby8870** [comment]
Top header bar for external content example from another app I like:

![screenshot_2017-02-10-05-58-28](https://cloud.githubusercontent.com/assets/18587752/22826107/40741c88-ef56-11e6-9ee2-6d15a7632fd4.png)

**Comment by gatsby8870** [comment]
Hello, I have only a few minor edits and then some questions for larger, new mobile app site work:

**Edits:**
1. Switch areas from where the text pulls from (aka we are just reversing what we have now):
   White tabs should pull from the "Pop up Text"
   "Details" page should pull from the "Body" field.
2. On "Details" page, move all text (headline and lower body text) "down" 10 pixels from top blue header
3. On "Details" page, move lower body text (aka all text except headline text) down another 10 pixels down 
4. For date format, if date is single digits, do not add a "0" before the number. For example, it should state "Feb 9" not "Feb 09"
5. In front of date field, add new field "Article Source" that pulls from [here](http://www.mortgagespeak.com/node/add/alpha-content). This will show where the content comes from. See attached image.

**Questions:**

1. How much for a loading icon screen that shows on app start-up?
2. How much to replace the "Copy URL" button (shown on "Details" page) with a button that enables sharing to other networks like Facebook, Google +, and "Copy URL" functionality?
3. What font size is used for the headline text on the "details" page?
4. If I wanted to add a new content type to be shown, how much would adding that cost? For example, I currently show "Recommendations for LinkedIN", "News", "Press Releases" and "Podcasts". My client is starting to offer podcasts so I would like to incorporate that. It would require an edit to the bottom row of icons as well. The content could be hosted at MortgageSpeak or directed elsewhere.


![article-source-plus-date-format-no-0](https://cloud.githubusercontent.com/assets/18587752/22883129/455c5dc2-f1b4-11e6-90cf-fbeda625d7a2.png)

**Comment by gatsby8870** [comment]
Note: The extra hour of time for item #5 above is approved. Thank you.

**Comment by hardik-addweb** [comment]
Hi @gatsby8870 
Edits:

-Switch areas from where the text pulls from (aka we are just reversing what we have now):
White tabs should pull from the "Pop up Text"
"Details" page should pull from the "Body" field.
> As per our discussion, we will not do anything for this change.

-On "Details" page, move all text (headline and lower body text) "down" 10 pixels from top blue header
> Done

-On "Details" page, move lower body text (aka all text except headline text) down another 10 pixels down
> Done

-For date format, if the date is single digits, do not add a "0" before the number. For example, it should state "Feb 9" not "Feb 09"
> Done

-In front of date field, add new field "Article Source" that pulls from here. This will show where the content comes from. See attached image.
> Done. Thank you for approving the time for this.

**Questions:**

-How much for a loading icon screen that shows on app start-up?
> Added ticket for the same [#77](https://github.com/snehal-addweb/Mortgagespeak/issues/77)

-How much to replace the "Copy URL" button (shown on "Details" page) with a button that enables sharing to other networks like Facebook, Google +, and "Copy URL" functionality?
> Added ticket for the same [#78](https://github.com/snehal-addweb/Mortgagespeak/issues/78)

-What font size is used for the headline text on the "details" page?
> Done. I have changed the size from 22px to 24px.

-If I wanted to add a new content type to be shown, how much would adding that cost? For example, I currently show "Recommendations for LinkedIN", "News", "Press Releases" and "Podcasts". My client is starting to offer podcasts so I would like to incorporate that. It would require an edit to the bottom row of icons as well. The content could be hosted at MortgageSpeak or directed elsewhere.
> Added ticket for the same [#79](https://github.com/snehal-addweb/Mortgagespeak/issues/79)

**Comment by gatsby8870** [comment]
Hello, two quick edits please:

"In front of date field, add new field "Article Source" that pulls from here. This will show where the content comes from. "

1. This looks great but there is not enough room for the Article Source name. Sometimes the name is longer than the field allows. Please increase possible character length. For example "Huffington Post" does not fit and it results in a line-break.

2. The "circle" that is shown after the above "article source" and before the "date" looks great. But there space after the circle (before the "date" is not as wide as the space after the article sournce (before the circle). Please increase the space **after** the circle to match the space before the circle.

![added-space-after-circle](https://cloud.githubusercontent.com/assets/18587752/23124620/984f689c-f733-11e6-87f3-96fbff2eeb5d.png)
