### ISSUE TITLE
Misc Site Edits

### ISSUE THREAD

**Issue by gatsby8870** [snehal-addweb/Mortgagespeak#74]
Hello, please perform these site edits:

**1. Sticky Pop Up**
Remove sticky pop up (but keep code if I want it later) and instead, load the article's "landing page" ([example](http://www.mortgagespeak.com/borrowing-power-increase-nationwide-2017)) in that browser's window.

**2. Landing page**
On article landing pages, replace the lower existing blue "Read More >>" button with the "Read full article" button show in below two images (full blue is mouse-over effect). Use new button size, shape, color and center location like picture.

![image](https://cloud.githubusercontent.com/assets/18587752/20869669/e61f3662-ba3c-11e6-809f-55377a3ced0f.png)

![image 1](https://cloud.githubusercontent.com/assets/18587752/20869672/f2cf6a4e-ba3c-11e6-8f68-1f329dc32ca5.png)

**3. Table date icon**
In the orange date icon by adjacent table content, change the day of the week at the bottom of icon to the year it was published (e.g. 2016)

**Comment by Krina-Addweb** [comment]
Hello Greg ,

Above mentioned points were done.
Please confirm do we have to remove Sticky popup from Editors pick?

Thanks.

**Comment by gatsby8870** [comment]
Hello, yes please remove the sticky pop from the Editor's Pick.

Thank you for asking and making sure!

**Comment by gatsby8870** [comment]
Hello, just a note that the landing page edit needs to be performed here as well: http://www.mortgagespeak.com/ads-for-pr

Thank you.

**Comment by gatsby8870** [comment]
Hello. Regarding item "**3. Table date icon**":

The center of this icon in large font should be the day's date (e.g. "15") and beneath it in smaller font should be the calendar year. It looks like the day was removed entirely and the yearly up into its spot (incorrect).

For the center day font color, please make #696B6F.

For the smaller calendar year text beneath, make font color: #FD9F1B.

Thank you!

**Comment by gatsby8870** [comment]
Hello, just a note:

1. The landing page edit needs to be performed here as well: http://www.mortgagespeak.com/ads-for-pr. The headline links now are not working at all.

Thank you.

**Comment by Krina-Addweb** [comment]
Hello Greg,

Above given changes were done.

Thanks.
