### ISSUE TITLE
Site work

### ISSUE THREAD

**Issue by gatsby8870** [snehal-addweb/Mortgagespeak#76]
My client, username "Rick" and pw: "Monkee5" cannot see the page: http://www.mortgagespeak.com/ads-for-pr

This page was built specifically for him,

Can you:

1. Enable this user to see it .
2. Add it to their lower gray bar row of links (e.g. Tracked Topics  Tracked Companies  Saved Articles  RGA Activity).

Additionally, in FF, the center nav bar button "Company Newsrooms" does not fit within the box and line breaks. Please resolve to one line.

Thank you!

**Comment by gatsby8870** [comment]
Hello,

Thank you for your work.

I believe this may still be a work in progress but when I log in and click the "Ads for PR" in the second gray row, the second gray header bar disappears and it shows ONLY the text "comes".

Thank you!

**Comment by roshni-addweb** [comment]
Hello Greg,

Above task is done. Please check.

Note: Now http://www.mortgagespeak.com/ads-for-pr will be visible to users who have "Ads for PR" role.
The links of "My page" will be taken down after certain number links as it affects the filters. Please check and let me know if you want any change for the same.

Total Consumed Hours: 2 hr 30 mins.

Thanks

**Comment by gatsby8870** [comment]
Hello, here are a few edits:

1. I have to start creating my newsletters earlier since I am working another job. Right now, I must wait until 12:01 am to start entering content that will be shown in the next day's newsletter. Please have any content entered into my site after 7:00 PM CST used for the next day. This will let me enter content at 7:00 PM for the next day's newsletter instead of me staying up until midnight.


2. Editor's Pick display on site. Please align the headline text so any line break still keeps headline text aligned with itself (the line breaks starts moved over more or less). See image.


![editors-pick](https://cloud.githubusercontent.com/assets/18587752/22974034/0bb06544-f346-11e6-9d21-e95d85aab321.png)

**Comment by roshni-addweb** [comment]
Hello Greg,

1. Please have any content entered into my site after 7:00 PM CST used for the next day.
=> Work in progress.

2. Editor's Pick display on site
=> Done.

Thanks

**Comment by gatsby8870** [comment]
Done. Thank you!
