### ISSUE TITLE
Audio file upload

### ISSUE THREAD

**Issue by gatsby8870** [snehal-addweb/Mortgagespeak#80]
Please enable my web site to upload MP3 file formats.

Please increase the file upload size to 10 Mb or whatever the max is (if less) since the files will likely vary somewhat in size.

This is for eventual output to my mobile app.

**Comment by roshni-addweb** [comment]
Hello Greg,

I have created new field for audio file "Podcast" in Alpha content type and max upload size in 8MB. Please check.

Thanks
