### ISSUE TITLE
Podcast audio functionality for mobile app

### ISSUE THREAD

**Issue by gatsby8870** [snehal-addweb/Mortgagespeak#81]
Please provide estimate to play Mp3 files uploaded to my web site to play within the app via a plug-in.

Thank you.

**Comment by hardik-addweb** [comment]
Hi @gatsby8870 ,

I have reviewed the requirement and it will take **3-4 hours** for us to play the audio in an application.

Please confirm the hours.

**Comment by gatsby8870** [comment]
This is approved.
