### ISSUE TITLE
Final app items for now :)

### ISSUE THREAD

**Issue by gatsby8870** [snehal-addweb/Mortgagespeak#82]
Hi, I thought I would set a new ticket for the final mobile app items in case you had questions or I asked for something difficult.

1. Rename bottom row icons:
 - "Rec. for LinkedIN" to "Editor Picks"
 - "News Headlines" to "News"
 - "Press Releases" to "P.R."
 - "Podcast" to "Podcasts"

2. Replace bottom row icon image. See attached. Images may be viewed [here](https://material.io/icons/) (see names below to find on page) and downloaded [here](https://github.com/google/material-design-icons/).

Icon names:
 - Editor Picks:	"grade"
 - News:		"assignment" (slight edit to top)
 - P.R.		"volume up"
 - Podcasts:	 "settings voice"

3. Remove vertical lines separating bottom row icons and text (see attached)

4. On app load, have the "News' section displayed and not the "Editor Picks" section (frmly. Recommended for LinkedIN)

5. Evenly distribute icons across row on "details" page (shown after tab click):
 - Question: Are there choices I can see for the social icon buttons?

6. Increase orange drop-down width and increase font size of text within.

7.  Edit splash screen (see attached). I flipped the text and icon, added a little margin space and edited the color orange (f07a22)

Questions:
Ads from Google AdMob will show in live app only?
Push notification functionality. How do I do this via drupal web site?

![4-logos-2](https://cloud.githubusercontent.com/assets/18587752/23245135/f360cf78-f94f-11e6-83ce-739109325668.png)

![new-splash-screen](https://cloud.githubusercontent.com/assets/18587752/23245141/fbf7f2a6-f94f-11e6-833f-4880116e75e8.png)

**Comment by hardik-addweb** [comment]
Hi @gatsby8870 ,

I have reviewed the edits, I will require 3 hours to complete the tasks.

Estimation Includes:

- Point #1, 2, 3, 4, 6, 7.

I want to discuss with you regarding point #5 on call and also the questions you have asked me.

Let's discuss on skype once you are available.

**Comment by gatsby8870** [comment]
The additional hours are approved.

Thank you very much.

**Comment by gatsby8870** [comment]
Hi, from our talk, we are using new icons from the ION link you provided. Attached is an image of the selected icons from this list for the "Editor Picks, News, P.R. and Podcasts" sections. The attached image is just a guide so you know you picked the right ones I listed below.

Editor Picks:		ion-star
News:			ion-android-list
P.R.:			keep existing (ion-speakerphone)
Podcasts:		ion-ios-mic


![4-ion-icons](https://cloud.githubusercontent.com/assets/18587752/23258899/02eea33a-f990-11e6-877b-6e085e6b449d.png)

**Comment by gatsby8870** [comment]
Hi, here are some app edits:

1. Increase width of orange drop-down like in image.

2. Remove extra space (see green arrow) above dark line

![editor-picks-bar-and-extra-space](https://cloud.githubusercontent.com/assets/18587752/23734946/1d920d0e-0448-11e7-846c-78b8092d7c34.png)

3.  Missing "s" on all section "details" pages

After clicking a content tab in all sections (Editor Picks, News, Press Releases, P.R., and Podcasts), the white text shown atop of the blue header is missing an editing "s". They read now incorrectly as:

- Editor Pick (should be Editor Picks)
- New (should be News)
- Press Release (should be Press Releases)
- Podcast (should be Podcasts)

4. Add a light background to the "back" arrow background for ll details pages. See Gmail image for general idea.

5. Remove the 3rd party advertising you added (e.g. "workaround). This is for the time being, not permanent.

6. Falling text on details page load. When I click the details page of any tab's content for the first time, the text that appears seems to enter the page from the top falling down. Is there a way to get it simply to load in place? This falling effect occurs only on that detail's page first load. Reloading the page shows it in place immediately (correct).

7. Splash Page. Remove the icon image (MS) and lower the text messages into the center of the page. Should stay in the center even on bigger screen devices (e.g. iPad).

**Comment by hardik-addweb** [comment]
Hi @gatsby8870 ,

We would require total **3 Hours** to complete these tasks.

Please send me the approval for moving ahead.

**Comment by gatsby8870** [comment]
This is approved.

Thank you!

**Comment by gatsby8870** [comment]
Hello, here is feedback plus a question/request:

Feedback:
Item #4 is not done though mentioned it is done.

The native advertising is missing from:

- Editor Picks and all sub pages (e.g. Lending, AMC, etc)
- Podcasts page

Question:

The default "loading" icon that is shown on the splash page is right over the text. Is there a way to remove the loading indicator on the splash page only? See attached.

Thank you!

![screenshot_2017-03-14-22-07-06](https://cloud.githubusercontent.com/assets/18587752/23931959/140fd350-0903-11e7-9d44-498a46ef8c0a.png)

**Comment by gatsby8870** [comment]
Regarding the "back arrow" effect, please see the attached image showing a lighter red box area around the back arrow when the arrow is depressed. This is the effect used in Gmail mobile and many other mobile app devices.

Thank you!

![screenshot_2017-03-15-14-04-09](https://cloud.githubusercontent.com/assets/18587752/23994436/f11da7da-0a12-11e7-8dc8-df6eb4caf385.png)

**Comment by gatsby8870** [comment]
Edit Item: Copy URL

Shown when clicking the "Copy URL icon" in the bottom right of any details page, the pop up message is great but please:

Center align the text "URL copied to clipboard!"
Replace the ending "!" with a "." (period).

Thank you.
