### ISSUE TITLE
iOS mobile application

### ISSUE THREAD

**Issue by gatsby8870** [snehal-addweb/Mortgagespeak#85]
This ticket is to set up the mobile app in iOS.

**Comment by hardik-addweb** [comment]
Hi @gatsby8870 ,

I will need almost **6 Hours** to setup the application in iOS platform.

This includes adding a proper provisional certificate and device id. It also included successfully integrating the code in iOS platform.

Could you please send your confirmation for the same.

**Comment by gatsby8870** [comment]
Ok to proceed.

Thank you.
