### ISSUE TITLE
RGA Ads

### ISSUE THREAD

**Issue by gatsby8870** [snehal-addweb/Mortgagespeak#86]
Create two charts from the content on this page **only** (http://www.mortgagespeak.com/my-page/ads-for-pr):

Chart 1. Pie Chart:

Slice 1: How many of these releases contain RGA Public Relations as a company tag.

Slice 2: How many of these releases do not have RGA Public Relations as a company tag. 

Slices should show "%" and "count" numbers.

Chart 2. Four column Chart:

	column 1: How many of these releases contain RGA Public Relations as one of the company tags
	column 2: How many of these releases contain William Mills Agency as one of the company tags
	column 3: How many of these releases contain Strategic Vantage as one of the company tags
	column 4: How many of these releases contain Depth Public Relations as one of the company tags
	column 5: How many of these releases contain none of the above company tags

![two-charts-for-rga](https://cloud.githubusercontent.com/assets/18587752/24130523/10024cee-0db7-11e7-9ab0-17c8afc57c33.png)

**Comment by gatsby8870** [comment]
Please begin. No estimate needed.

If you come across anything very time intensive, just let me know. But ok to begin.

**Comment by gatsby8870** [comment]
Thanks for the work so quickly!

Here is some feedback:

Q. Why don't the numbers match up? The numeric counter in orange counts all the press releases on this page (aka press releases with this RGA top banner ad). The charts should be pulling their data from those releases so the numbers added up so equal the numeric orange counter.

Edit.

Add Pie Chart Title: "RGA-Branded Press Releases"
(orange) "From RGA"
(green) "Not From RGA)

Add Column Chart: "RGA-Branded By Company"
(organize columns from left to right): "Depth Public Relations  RGA Public Relations  Williams Mills Agency  Strategic Vantage  Other"

Add to the column chart pop-up a period "." after the "No" to be like this "No." (aka number abbreviation)

Add a date filter

**Comment by Krina-Addweb** [comment]
Hello Greg,

Please check the above mentioned changes over mortgagespeak.com

Thanks.

**Comment by gatsby8870** [comment]
Hi, thank you for the update.

Edits:

1. Reset button not working

2. Please update the orange counter box to be like the attached image.

![rga-branded-counter-placement](https://cloud.githubusercontent.com/assets/18587752/24318647/8fa2f2f6-10d6-11e7-8672-26e28e52365d.png)

3. In the pie chart, display the number AND percentage in pie chart slices by default (not just % like now).

**Comment by Krina-Addweb** [comment]
Hello Greg,

Please check last given edits.

Note: If pie chart slices are too small then you will not being able to view "percentage & value"

Thanks.

**Comment by gatsby8870** [comment]
Hi, thanks for the quick work! I appreciate it.

Let's revert back to percentages for the pie slices. I was hoping the numbers would be stacked and therefore not be so small. It is too small now with the "number" added. So let's just revert.

Thank you!

**Comment by gatsby8870** [comment]
Please change the title to "Company Press Releases with RGA AD" from "RGA-Branded By Company".

Thank you.
