### ISSUE TITLE
Web Site edits

### ISSUE THREAD

**Issue by gatsby8870** [snehal-addweb/Mortgagespeak#89]
Hello, kindly perform the following items:

1. Have the headlines links in the table open in a new browser window: http://www.mortgagespeak.com/my-page/ads-for-pr

2.  All tables show a lower Twitter icon below them. It is not functioning properly; shows bad code when pressed.

**Comment by Krina-Addweb** [comment]
Hello @gatsby8870,

For RGA Ads above mentioned both the points are done, for rest of all the pages, the work is in progress for point #2.

Thanks,

**Comment by Krina-Addweb** [comment]
Hello @gatsby8870,

Please Check #2 changes over mortgagespeak.com for all pages, we made changes for all pages & let me know if there are any further Changes.

Thanks,
