### ISSUE TITLE
Redirect to mobile app

### ISSUE THREAD

**Issue by gatsby8870** [snehal-addweb/Mortgagespeak#91]
Hello, could you provide a time estimate to have mobile web visitors being directed to download my mobile app and not see the mobile web site version?

I saw a Drupal module for this.

Thank you!

**Comment by roshni-addweb** [comment]
Hello Greg,

Yes, module is available for the same, but need to configure and check if it is working as per our needs.

Estimate : 2 - 3 hrs approx

Thanks

**Comment by gatsby8870** [comment]
Ok please do this.

Thank you.

**Comment by roshni-addweb** [comment]
Hello Greg,

Estimation for adding buttons on home page : 2hrs  

Thanks

**Comment by gatsby8870** [comment]
Please proceed.

Thank you.

**Comment by roshni-addweb** [comment]
Hello Greg,

Please check home page in mobile and let me know if you want any further changes.

Thanks

**Comment by gatsby8870** [comment]
Hi, I was hoping we could have the page would look only like the attached. 

Thank you.

![idea](https://cloud.githubusercontent.com/assets/18587752/26756306/c3560fc8-4864-11e7-816e-dc103204d7d4.png)

**Comment by roshni-addweb** [comment]
Hello Greg,

Please check above changes. Please note that redirection after 10 seconds is not removed. Let me know if you want any changes.

Thanks

**Comment by gatsby8870** [comment]
It looks great.

Please remove the redirection and we're done with this.

Thanks again!

**Comment by Krina-Addweb** [comment]
@gatsby8870 : Please Check the Redirection removal from live site for mobile devices.

Thanks!..

**Comment by gatsby8870** [comment]
Hello, I noticed in my mobile browser when the viewer goes to MortgageSpeak.com, they do see the above image. However, if the scroll down, they also see the quotes and large ad.

I only want mobile users to see the above image.

Thank you.

**Comment by Krina-Addweb** [comment]
@gatsby8870, Please check mentioned changes in mobile devices & let us know.

Thank you.
