### ISSUE TITLE
How to add Drupal Ad to podcasts screen from drupal admin panel 

### ISSUE THREAD

**Issue by hardik-addweb** [snehal-addweb/Mortgagespeak#93]
Below is the video that shows how to add Drupal Ad to podcasts screen from drupal admin panel.

Please review the video and let me know if any issue.

https://www.screencast.com/t/4JFt88dX6mH

We have spent 30 mins to create this video.

**Comment by gatsby8870** [comment]
Got it. The issue was there was not enough content to show an ad. Without content, the ads cannot be displayed between the content. Something like that. Thanks.

**Comment by hardik-addweb** [comment]
Hi @gatsby8870 ,

So do we need to send you any updated build to you?

**Comment by gatsby8870** [comment]
Sure, send me the build first. Thanks.
