### ISSUE TITLE
Web site edits

### ISSUE THREAD

**Issue by gatsby8870** [snehal-addweb/Mortgagespeak#94]
Hello, this thread is for my web site (non-mobile work).

1. Can you please center align the web site in the browser? Right now, it is left-aligned and I cannot see the left column nav links.

2. Can you add a new row above the left column nav links that says "Breaking news topics"? Please see the attached image.

Thank you!

![home-page-redesign-6-11-17](https://user-images.githubusercontent.com/18587752/27269030-155c4dbc-5479-11e7-99f4-5beda341a669.png)

**Comment by Krina-Addweb** [comment]
@gatsby8870, Above given task, were done over live. Please check the changes & let us know.

Thank You.
